_src/_assets/css/_states.scss, _src/_assets/css/all.scss, _src/_templates/base.njk, _src/_templates/states.njk
Hello all! In this branch, I’ve got a speculative sketch of some styles for the State Notes page. I would really, really like any feedback y‘all might have to offer.
Here’s a short screen recording: https://www.dropbox.com/s/y51bhbnecy3kwc1/state%20notes.mov?dl=0
And here are some quick screenshots:
I’m coming at this content relatively cold, so any feedback/notes would be really welcome. Specific things I’m wondering about:
- Does a grid/card layout feel appropriate at wider screens?
- Does positioning the notes underneath each state’s table feel appropriate?
Let me know how this feels to you! Happy to take another crack at this okay thank youuuuuu
=> Initial style sketch for the State Notes page

_src/_assets/css/_layout.scss, _src/software.md
Created a software page in response to issue #6
=> Add software page, update styles for nested lists

_src/_assets/css/_states.scss, _src/_data/sheets.js, _src/_templates/states.njk
Just a basic table on top of notes pg to give example of making another table.
=> us total on notes pg

_src/_data/sheets.js
=> Change name of VI

_src/index.md
=> Add mention of 5 U.S. territories to home page

_src/about-tracker.md, _src/api.md
There were a few questions, albeit because of a data mistake, regarding if the data was cumulative or per day. We can fix the data mistake but let's also have the answers in our docs.
Refs #21
=> Document cumulative nature of data

_src/_templates/partials/header.njk
we have [new words 4 our navigation](https://github.com/COVID19Tracking/website/issues/63#issuecomment-601415386)
these are the words
_they’re v good words_
=> Navigation copy updates (per #63)

_src/webappmanifest.njk
Noticed that the webappmanifest.json file was invalid JSON. Fixed.
=> Fixed webapp manifest

_src/newsroom-expert-faq.md
👋 Just updating some contact info for routing purposes!
=> Update NewsNerdery contact details.

.eleventy.js, _src/_data/sheets.js, _src/_templates/index.njk, _src/index.md
This replaces the static press links on `index` with ones from the API
=> Add press links

_src/_templates/state.njk, _src/_templates/states.njk
Shows the data quality grade on the data page and individual state pages.
=> Added state grade

_src/_assets/css/_state.scss, _src/_templates/state.njk
Adds Twitter icons to the state pages instead of the Twitter link in text:
New:
Old:
=> State page twitter icons

_src/_templates/state.njk, _src/_templates/states.njk, _src/_templates/us-daily.njk
=> Add hospitalized values to data tables

_src/_templates/us-daily.njk
Making a difference here... :-D
=> Remove outdated comment

_src/_assets/css/_states.scss, _src/_assets/css/_tables.scss, _src/_templates/state.njk, _src/_templates/states.njk
Edit: no longer a WIP
This closes #103 and may address #101 .
Edit: this closes 2/5 of #101 
More description to come soon.
=> Tables redesign (Closes #103, partially closes #101)

_src/visualizations.md
I updated the website domain, making the same changes here
=> Update Kaiyu Hsu site in visualizations.md

_src/_assets/css/_state.scss, _src/_templates/state.njk, _src/_templates/states.njk
=> Identify state history

_src/_assets/css/_states.scss
=> More padding for states nav near medium viewport

_src/_assets/css/_tables.scss, _src/_templates/state.njk, _src/_templates/us-daily.njk
=> Added table scroll for large tables on mobile

_src/about-team.md
Updates contributors list, closes #105
=> About team refactoring

README.md, gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/components/layout/index.js, src/content/pages/about/api.md, src/content/pages/help.md, src/content/pages/help.mdx, src/content/pages/project/team.md, src/content/snippets/data.md, src/data/navigation/about.yml, src/data/navigation/footer.yml, src/scss/global.scss, src/templates/state.js, src/utilities/format-date.js
- Added screenshot links
- Formatting for dates
- Automatic header URLs per #111 
- Synced content with the current master.
=> Screenshots, date formatting

package-lock.json, package.json
Fixes #148 
Bumped acorn and ran `npm audit` to catch a few other security issues.
=> Bump acorn, audit NPM

_src/dashboard.md
Added a non-visible link to the data page after a map so users with screen readers can access the data.
=> Added a11y link to dashboard map

_src/_assets/css/_charts.scss, _src/_assets/js/d3-chart.js, _src/dashboard.md, d3-chart.js, dashboard-charts.js
This chart is operational but it needs a bit of work:
=> cdc chart operational but needs a bit of work

.eslintrc.js, README.md, gatsby-config.js, package-lock.json, package.json, src/components/common/button.js, src/components/common/detail-text.js, src/components/common/press.js, src/components/common/summary-table.js, src/components/layout/footer.js, src/components/layout/header.js, src/components/layout/index.js, src/components/seo.js, src/content/pages/help.md, src/pages/404.js, src/pages/data/historical.js, src/scss/components/common/detail-text.scss, src/stories/06-Detail-text.stories.js, src/stories/12-Press-links.stories.js, src/templates/content.js, src/templates/state.js, src/utilities/format-date.js
Turned on ESlint in Gatsby
Some missed formatting
Changed totals
=> Readme content, ESLint

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/components/common/alert.js, src/components/common/container.js, src/components/layout/development-warning.js, src/components/layout/header.js, src/components/layout/index.js, src/content/pages/index.mdx, src/pages/data/index.js, src/scss/components/common/container.scss, src/scss/components/development-warning.scss, src/scss/components/header.scss, src/scss/components/hero.scss, src/scss/global.scss, src/scss/pages/data.scss, src/stories/00-Layout.stories.js, src/stories/09-Tables.stories.js, src/stories/13-Development-warning.stories.js, src/stories/15-Container.stories.js, src/templates/content.js, src/templates/state.js, src/utilities/typography.js
Added Typography.js so we have a baseline
Created a "Container" component
Renamed the header a bit because it used the class name "container"
Added a special "noContainer" to frontmatter so that pages like the homepage can control where containers appear
Added the container manually to homepage per above
Installed Reflexbox for simple flexboxing
Added basic state information to the /data page to mirror what's live.
=> Data page, basic layout

_src/_assets/js/dashboard-charts.js, _src/dashboard.md
- Spelling fix
- fixing total test count number in text
=> Goleary dashboard specimen

src/content/pages/about/api.md, src/content/pages/about/index.mdx, src/content/pages/help.md, src/content/pages/project/team.md, src/content/snippets/us-daily.md
Updated pages to reflect the past few days' content updates.
=> Gatsbyjs content sync mar 27

CONTRIBUTING.md
Fixes #25 
Would love feedback on this, I was mostly pulling from a variety of other similar projects. This should only be scoped to contributing to the website repository. We can link to another location on how to help with the entire CTP.
=> Feedback needed: Added contributing doc

_src/visualizations.md
=> Add testing.predictcovid.com to Data Visualizations page

_src/_assets/js/d3-area-chart.js, _src/_assets/js/d3-bar-chart.js, _src/_assets/js/dashboard-charts.js, _src/dashboard.md
Not a complete implementation as the special case handling for states with super big numbers (like NY) isn't yet implemented but there's one less chart using britecharts, but I think if approved we can merge at this stage to keep it close to `dashboard`
=> Refactor out area chart builder

_src/_assets/css/_charts.scss, _src/_assets/js/d3-area-chart.js, _src/_assets/js/dashboard-charts.js, _src/dashboard.md
=> Add stay at home annotation

src/components/pages/homepage/press-list.js, src/content/pages/index.mdx
Added a component that lists recent articles, filtering by ones that should be displayed and has a title
=> Gatsbyjs homepage press

package-lock.json, package.json, src/scss/colors.scss, src/scss/components/common/infobox.scss, src/stories/02-Colors.stories.js
Added a color palette for SCSS files, storybook with automatic WCAG levels, and made infoboxes use the new color variables.
=> Added default colors

_src/_data/sheets.js
If the screenshot API is unavailable, the website will still build.
=> Handle missing screenshots

static/_redirects
Made sure the netlify redirects file still worked.
=> fix(code): Updated redirects

src/stories/02-Colors.stories.js
Add text and color hex to swatches.
=> feat(storybook): Better swatches

src/scss/components/footer.scss
Fixes #259 - This just changes the color, the layout is already captured in #257
=> fix(design): Update color in footer

src/content/snippets/data.md, src/pages/data/index.js, src/scss/pages/data.scss
This adds columns for very wide viewports and adds a "back to top" link on the states page.
=> V2 data page updates

src/pages/index.js, src/scss/components/hero.scss
- Fixes the breakpoints for the flexboxes on the homepage
- Changed hero to use breakpoint variables
=> Fix flexbox on homepage

README.md, src/components/common/summary-table.js, src/components/pages/homepage/press-list.js, src/components/pages/homepage/press-logos.js, src/pages/index.js, src/scss/global.scss
Fixed a few missing ID errors, a11y tweaks. Added an a11y-only class
=> A11y and React ID fixes

src/components/pages/homepage/press-list.js, src/pages/index.js, src/scss/components/common/detail-text.scss, src/scss/components/common/infobox.scss, src/scss/components/common/summary-table.scss, src/scss/components/header.scss, src/scss/components/hero.scss, src/scss/components/pages/homepage/press-list.scss, src/scss/components/pages/homepage/press-logos.scss, src/scss/pages/homepage.scss
Ok, this handles many of the type and spacing items on #276. This could use your eyes @schwartzadev @kevee when you have a moment!
=> Gatsby design adjustments

package.json, src/scss/colors.scss, src/scss/components/common/detail-text.scss, src/stories/02-Colors.stories.js
Darkened detail text for WCAG AAA
Re-enabled Storybook
Added variable name to swatches
=> fix(a11y): Darken detail text, re-enable Storybook

src/components/common/hero.js, src/components/layout/header.js, src/components/pages/homepage/press-list.js, src/pages/index.js, src/scss/components/common/container.scss, src/scss/components/common/detail-text.scss, src/scss/components/footer.scss, src/scss/components/header.scss, src/scss/components/hero.scss
- Updates the detail text formatting and spacing
- Uses the Container component on the header and footer so that they are the same width as content
=> Visual tweaks

src/components/common/summary-table.js, src/pages/data/index.js, src/scss/components/common/summary-table.scss, src/scss/pages/data.scss
This resolves @beep 's [feedback](https://github.com/COVID19Tracking/website/issues/276#issuecomment-606777052) in #276
=> Data page updates See #276

README.md, gatsby-config.js, src/components/common/state-data.js, src/components/pages/homepage/visualization.js, src/components/pages/homepage/visualizations.js, src/pages/data/index.js, src/pages/index.js
- moves the State component to its own file
- moves the visualizations into components
* parent `visualizations.js`
* child `visualization.js`
=> Refactor State and Viz JS Components

src/scss/colors.scss, src/scss/components/header.scss, src/scss/components/hero.scss, src/scss/global.scss
Resolves @jasonsantamaria 's [comments](https://github.com/COVID19Tracking/website/issues/276#issuecomment-606719834) from #276 .
=> Update Colors 276

src/data/navigation/header.yml, static/_redirects
=> fix: Redirects & header link

src/pages/index.js, src/scss/pages/homepage.scss
Made the "why this matters" pane on the homepage editable in Contentful.
=> feat(content): Added snippet to homepage

src/components/common/table.js, src/scss/templates/state.scss, src/templates/state.js
=> State page table styles (closes #321)

src/pages/index.js, src/scss/pages/homepage.scss
Another teeny atomic PR, this time re: #313. Also took out what appears to be a typo'd/extraneous class.
=> fix(site): Tweaking homepage's Get Involved

src/components/common/summary-table.js, src/pages/data/index.js, src/pages/data/us-daily.js, src/templates/state.js
Changed the "Total tests" field to pull from `totalTestResults`
=> fix: Change source field for totals

build/datasources/screenshots.js, build/datasources/states.js, build/datasources/statesDaily.js, build/datasources/usCurrent.js, build/datasources/utils.js, build/handlers/csv.js, build/handlers/html.js, build/handlers/save.js, build/handlers/utils.js, build/package-lock.json, build/package.json, build/test.js
- Cleaning up paths. Using /states/[state] instead of /state/[state].
- Added basic html table output to help debug. It's also been requested.
- Secondary screenshots added.
=> Api 2 - Cleanup File Structure

src/components/layout/footer.js, src/pages/index.js, src/scss/components/footer.scss
fixes #319
Added back to top link
Re-centered content
Link color is fixed.
=> Footer design 319

src/data/navigation/header.yml
=> fix: Added Data API to global navigation

_src/_assets/css/_dashboard.scss, _src/_assets/js/d3-legend.js, _src/_assets/js/dashboard-map.js, _src/dashboard.md
=> feat(dashboard-map): multiple colors for chloropleth

_src/_assets/css/_dashboard.scss, _src/_assets/js/d3-bar-chart.js, _src/_assets/js/dashboard-charts.js, _src/dashboard.md
Move away from graphics next to text to a single column of alternating text and charts
=> Adjust dashboard layout to be single column

package-lock.json, package.json, src/__tests__/build-test.js
=> feat: Add build success test

src/pages/data/index.js, src/pages/data/us-daily.js
Data pages were missing navigation queries that point to Contentful pages.
=> Page nav in data pages

src/scss/components/header.scss, src/scss/global.scss
=> Fix nav colors (closes #377)

src/components/common/summary-table.js, src/pages/data/index.js, src/templates/state.js
Thanks to the data team for getting this spun up! And @webmasterkai for the API side of things.
Also closes #392 with the Contentful data that @kevee set up :+1:
=> Add outcomes data

src/components/common/hero.js
The hero component was linking to /about instead of /about-data
=> fix: Link to about data incorrect

gatsby-config.js, src/components/layout/seo.js
Added back a missing meta tag.
=> Add meta description

src/pages/data/index.js
This pull request fixes #416, by sorting state navigation by the abbreviations, and sorting the state data by the state name, in /data/.
=> fix(design): Changed state display to order states alphabetically.

src/utilities/typography.js
Fixes COVID19Tracking/website#415.
=> Decrease header line height

build/index.js
Hopefully this makes them easier to read in Netlify output.
=> Make API errors red

src/pages/dashboard/_AreaChart.js, src/pages/dashboard/_SmallMultiplesAreaCharts.js, src/pages/dashboard/dashboard.scss
=> Update small multiples data for stay at home orders and add to charts

package-lock.json, package.json, src/components/common/state-data.js, src/components/pages/data/state-nav-no-script.js, src/components/pages/data/state-nav.js, src/pages/data/index.js, src/scss/components/common/state-data.scss, src/scss/pages/data.scss
Related to #325 
This adds a Combobox element to the right/bottom of the data page that jumps people to a selected state.
The existing state nav element is retained and hidden except with JS turned off.
=> feat(design): Added jump-to-state combobox

src/pages/dashboard/_MapContainer.js, src/pages/dashboard/charts/_ChoroLegend.js, src/pages/dashboard/charts/_Map.js, src/pages/dashboard/map-container.scss
- Updates orange color scheme
- Decreases toggle font size, updates "Choropleth" to "Chropleth Map"
- Moves/rewords "per one million people" text
Fixes COVID19Tracking/website#349.
=> Adjust legend of choropleth

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md
Updated the contributing docs to include an email for security issues.
=> feat(docs): Added security contact

src/pages/index.js, static/_redirects
=> fix: In the press page moved

src/pages/dashboard/_CDCComparisonContainer.js
Still needs some styling work but good enough for review/merge and we can break out other issues to fix the small things.
=> Add basic CDC chart with data from GraphQL API

src/pages/dashboard/_MapContainer.js, src/pages/dashboard/map-container.scss
=> feat: add date lable for map-time-scrubber, re: #441

src/pages/dashboard/_MapContainer.js, src/pages/dashboard/_UsCumulativeDeathsContainer.js
=> Standardize language around testing in graphics

src/components/layout/footer.js
Fixes #470 
Adds an accessibility statement link to the footer of the website. The page itself is in Contentful.
=> chore: Add accessibility statement link

src/pages/dashboard/_MapContainer.js, src/pages/dashboard/map-container.scss
Fixes #485 
Tested on Chrome, Safari and Firefox on OS X.
=> fix(visualization): Style map slider

src/pages/dashboard/_MapContainer.js
[354](https://github.com/COVID19Tracking/website/issues/354)
Updated:
positive Cases to positive tests, total Tests to total tests
Before
After
=> fix: update capitalization for choropleth dropdown

src/pages/dashboard/charts/_Map.js, src/pages/dashboard/map-container.scss
=> fix(visualization): Make sure outline of hovered state is on top

src/components/pages/data/state-nav-no-script.js
Fixed capitalization of links in the no JS nav, closes #521
=> fix(no-js-nav): in-page links to states

src/pages/dashboard/_CDCComparisonContainer.js, src/pages/dashboard/_StateCumulativeDeathsContainer.js, src/pages/dashboard/_UsCumulativeDeathsContainer.js, src/pages/dashboard/index.js
Updated text and some minor structural changes as part of #537. Going to do the rest of them after this is merged to keep the PRs focused
=> Update dashboard text

src/pages/dashboard/_StateCumulativeTestsContainer.js
I don't know about the styling of the state names/links.  I can update the PR with any design guidance.
=> fix(dashboard): link data on sm multiples state titles #543

src/pages/dashboard/dashboard.scss
=> Limit changes on :focus

src/components/common/blog-lede.js, src/components/common/blog-lede.module.scss, src/components/common/blog-list.js, src/components/common/byline.js, src/components/common/byline.module.scss, src/components/layout/header.js, src/components/layout/header.module.scss, src/components/layout/index.js, src/data/navigation/header.yml, src/pages/blog.js, src/pages/index.js, src/templates/blog-post.js, static/_redirects
Related to #541 
This includes ledes, bylines, and style changes to the blog section.
=> [WIP] Blog post styles

src/components/common/container.module.scss
=> fix: Margin for text heavy containers

src/pages/blog.js
=> Post-blog launch updates

src/data/navigation/header.yml, src/pages/race.module.scss
Fixes #590 
- Reordered nav
- Fixed logo size on race project landing page
=> Race project navigation 590

src/pages/data/index.js, src/pages/race.js
Added the racial data page to the why it matters navigation
=> fix: Navigation for racial data page

src/components/layout/footer.js, src/pages/index.js, static/_redirects
=> Homepage and footer links

src/stories/2-components/15-Charts.stories.js
=> fix(storybook): broken imports

src/pages/race.module.scss
Oy, I’m a dummy – messed that up in last night’s PR.
Closes #603
=> Update race landing page font size, spacing

gatsby-config.js, src/components/common/format.js, src/components/common/infobox.js, src/components/common/summary-table.js, src/components/pages/data/state-data.js, src/components/pages/state/state-history.js, src/pages/data/index.js, src/pages/data/us-daily.js, src/templates/state.js
See e21c64ee94a87c58cadbc642c5e150c2d8f6cac9 for details about the AM/PM implementation in `gatsby-config.js`
=> Text, date updates (closes #588)

build/datasources/index.js, build/datasources/volunteers.js, build/handlers/slack.js, package-lock.json, package.json
Starting work on https://github.com/COVID19Tracking/website/issues/496
=> feat(api): add public volunteers to _data to support displaying volunteer credits on the website

.github/ISSUE_TEMPLATE/config.yml, .github/stale.yml
- Added [Stale bot](https://github.com/apps/stale)
- Made security issues link open a mailto.
=> Config stale bot, mailto link for security issues

gatsby-config.js, package-lock.json, package.json
- Cleaned up unused variables and tick usage in config file
- Audited and removed unused packages
- Moved developer dependencies to the right place
- Ran `npm audit` and fixed findings
=> chore: Cleanup package.json and gatsby config file

.github/stale.yml
The stalebot was using the wontfix label. Changed to a 'stale' label
=> Changed stalebot to use stale label

build/handlers/index.js, build/handlers/sheets.js, build/index.js
This adds a more clear error for whenever fetching Google Sheets fails
=> feat(sheets): handle Google Sheets HTTP errors

src/components/pages/state/screenshots.js
=> chore(screenshots): use FormatDate

.circleci/config.yml, src/__tests__/components/charts/__snapshots__/area-chart.js.snap, src/__tests__/components/charts/__snapshots__/bar-chart.js.snap, src/__tests__/components/charts/__snapshots__/horizontal-bar-chart.js.snap, src/stories/2-components/13-Charts.stories.js
Updated test snapshots for chart components.
=> chore: Update test snapshots for charts

src/pages/about-data/visualization-guide/_StateCumulativeTestsContainer.js, src/pages/about-data/visualization-guide/_UsPositiveAndTotalTestsContainer.js, src/pages/about-data/visualization-guide/index.js
=> fix(dashboard): final text revisions

.github/PULL_REQUEST_TEMPLATE.md
This comments out the "go live" section of the PR template by default.
=> chore(pr-template): comment out go-live time section

build/__tests__/handlers/__snapshots__/index.js.snap, build/__tests__/handlers/index.js, build/datasources/index.js, build/handlers/__mocks__/save.js, build/handlers/index.js, jest.config.js, package.json
This adds a bunch of tests for the `build/handlers/index.js` module.
=> Build handler unit tests

src/components/pages/blog/blog-list.js, src/pages/blog.js
Fixes missing react keys
Fixes #699
=> fix: Undefined blog key

build/datasources/states.js
This updates the API notes section for updating to the completenessGrade field
=> Update Completeness Grade API Notes

__mocks__/sample-state.js, build/datasources/index.js, build/datasources/states.js, src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/__tests__/components/pages/state/__snapshots__/state-grade.js.snap, src/components/pages/data/state-data.js, src/components/pages/state/state-grade.js, src/pages/data/index.js, src/templates/state.js
This PR:
1. Adds a new sheet source to the API using the new state comprehensive grade
2. Maps that source to the `states/current` file as a new field called `comprehensiveGrade`
3. Keeps the old grade stuff untouched
4. Changes the website to use the new `comprehensiveGrade` field
=> feat: Add comprehensive grade

jest.config.js, setupTests.js, src/__tests__/components/pages/data/__snapshots__/state-nav.js.snap, src/__tests__/components/pages/data/state-nav.js, src/__tests__/components/pages/state/screenshots.js, src/components/pages/data/state-list.js, src/components/pages/data/state-nav.js
Adding tests for and improving coverage for `src/components/pages/data/state-nav.js`. The coverage for this component was very low.
=> Add some tests for state-nav.js component

build/datasources/volunteers.js
Fixes https://github.com/COVID19Tracking/website/issues/714
=> fix: stagger slack API calls to avoid rate limits

src/pages/about-project/index.js
Adds a snippet for past contributors to the about us page.
Fixes #704
=> chore: Added past contributors snippet

.circleci/config.yml, .storybook/config.js, package.json
- **Prevent test memory errors** - Fixed memory errors in tests by switching to single-thread.
- **Fixed build errors in Storybook** - Storybook was calling Typography, which has been gone since #638 
- **Adds QA testing for Storybook** - Add storybook to CircleCI
=> CI memory issues, Storybook build error, CI test for storybook

src/__tests__/components/layout/__snapshots__/footer.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/components/layout/footer.js, src/components/layout/footer.module.scss
This PR corrects a small layout bug in the footer (#715), which was introduced in #638! There’re also a few minor spacing/alignment fixes, which should tighten up the component a bit.
Fixes #715.
Not time-sensitive; can go out whenever!
no post-merge steps it’s just css times
=> Alignment and spacing adjustments for footer, closes #715

src/pages/index.js
Added CTA for racial data tracker
Fixes #732
=> chore: Add CTA to homepage

jest.config.js, package-lock.json, package.json, src/__tests__/components/pages/state/__snapshots__/state-history.js.snap, src/components/pages/state/state-history.js
- Added timezone to screenshot column
- Made all Jest testing run in America/New_York timezone
Fixes #716 
This is my atonement for screwing up #728
=> feat: Add timezone to screenshots

functions/api-proxy.js
Fixes CSV files in the API proxy.
=> chore: Fixed CSV files

static/_redirects
=> chore: revert to covid.cape.io for backend

package-lock.json, src/pages/api.js
This merges content from Contentful and the new API sandbox from #517  into one page.
=> feat: Merge API page and swagger

static/_redirects
Based on a sample of 32,000 API calls being proxied to the old API endpoint at three different times of the day, this PR adds redirects to all possible used combinations of old API calls.
=> [WIP] Redirect API endpoints

gatsby-config.js, src/__tests__/components/common/__snapshots__/infobox.js.snap, src/__tests__/components/common/__snapshots__/summary-table.js.snap, src/__tests__/components/common/table.js, src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/__tests__/components/pages/state/__snapshots__/state-history.js.snap, src/__tests__/components/utils/format.js, src/components/common/infobox.js, src/components/common/summary-table.js, src/components/common/table.js, src/components/common/table.module.scss, src/components/common/timezone.js, src/components/pages/state/state-history.js, src/components/pages/state/state-history.module.scss, src/components/utils/format.js, src/pages/data/us-daily.js, src/scss/global.scss, src/stories/2-components/09-Tables.stories.js
This PR improves typography and general styling of tables.
Related to #457, fixes #721
=> feat(tables)

netlify.toml
Updates the environment for Algolia
=> chore: update environment command for production

src/templates/blog-post.js
Removes the featured image from the blog, builds successfully without any featured images in Contentful
=> chore(blog): rm featuredImage from query

src/__tests__/components/layout/__snapshots__/header.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/__tests__/components/pages/data/__snapshots__/state-nav.js.snap, src/__tests__/components/search/__snapshots__/search-result-section.js.snap, src/__tests__/components/search/__snapshots__/search-result.js.snap, src/components/layout/header.js, src/components/layout/search-autocomplete.js, src/components/pages/blog/byline.js, src/components/pages/data/state-nav.js, src/components/search/search-result.js, src/components/search/search-result.module.scss, src/pages/search.js
Calibre caught some form and button label issues. This PR Fixes:
- Missing labels on search form buttons
- Missing label on search form input
- Heading order on search results page
=> fix(a11y): Fix accessibility of form labels, heading order

build/__tests__/post-build/v1/states/daily.js, static/api-docs/COVID-tracking-endpoints-1.0-docs.json
Adds two new fields to daily API and API docs: `grade` and `lastUpdateEt`
=> chore: Add two new fields to spreadsheet

src/components/pages/homepage/cta-link.module.scss
Changes the hover color for CTA links from purple to off-black.
=> fix(homepage): cta hover color [minor]

src/components/pages/homepage/large-project.js
Typo on homepage.
Fixes #806 (again)
=> chore(copy): Remove double the

src/components/layout/header.module.scss, src/components/pages/homepage/header-hero.js, src/components/pages/homepage/header-hero.module.scss
- Darkens color in header and chart
- Redesigns color legends
- Resizes fonts
- Switches y axis to left when header stacks
- Brings chart higher up the hero element
Fixes #807
Fixes #808
Fixes #809
=> Refactor homepage chart design.

src/pages/contact/index.js
- Adds a hidden `subject` field for Front
- Reorders the values in "What are you contacting us about?"
Fixes #839 
Fixes #836
=> chore: Contact form subject line & reorder reasons 

build/datasources/screenshots.js, netlify.toml, static/_redirects
- Changes the s3 endpoint for screenshots to the new bucket
=> chore: Update screenshot source

gatsby-config.js, src/components/pages/blog/categories.js, src/components/pages/blog/table-content-block.js, src/components/pages/blog/table-content-bock.module.scss, src/templates/blog-post.js
Add table support to blog posts.
=> feat(content): Added table support

src/pages/data/index.module.scss
Fixes the z-index on the state navigation bar in the data page when it is sticky.
Fixes #853
=> fix(design): Fix sticky header zindex

src/components/pages/blog/author-footer.js, src/components/pages/blog/table-content-bock.module.scss, src/templates/blog-post.js
Fixes the text-align of tables, twitter links for authors with no twitter account, and adds some spacing to the top of blog posts.
=> chore: Fix table alignment, twitter link

src/__tests__/components/layout/__snapshots__/header.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/components/layout/header/index.js
Changed from "from The Atlantic" to "at The Atlantic"
Fixes #867
=> chore: Update Atlantic credit

src/components/pages/race/charts/county-chart-legend.js, src/components/pages/race/multiplier-highlight.js, src/components/pages/race/multiplier-highlight.module.scss, src/components/pages/race/national-chart.js, src/components/pages/race/national-chart.module.scss, src/components/pages/race/paragraph.module.scss, src/pages/race/index.js
- Integrates data from new API endpoint
- Adds donut charts.
=> feat: Added donut charts

src/components/pages/blog/image-content-block.js
Fixed caption field for blog images
=> chore: Fix missing caption field

src/pages/about-data/visualization-guide/index.js
Update the text in the visualization guide to reflect that the CDC does currently publish data.
Does not include updating the chart (part of #898) in this PR so we can get the page updated and then work on adding in the visualization.
Addresses part of #898
=> feat(viz-guide): Update text to note CDC report

src/components/common/landing-page/header.js, src/components/common/landing-page/paragraph.js, src/components/common/landing-page/paragraph.module.scss, src/components/pages/race/dashboard/state-separate.js, src/components/pages/race/dashboard/states.js, src/components/pages/race/multiplier-highlight.module.scss, src/pages/race/index.js
- Tightens top headlines about black lives lost
- Adds special notes to bottom of dashboard
=> CRDT dashboard: special notes

gatsby-node.js, src/components/pages/race/dashboard/state-combined.js, src/components/pages/race/dashboard/state-separate.js, src/components/pages/race/dashboard/states.js, src/components/pages/race/dashboard/table-notes.js
- Add explicit type definitions for note fields
- Prevents issues where if there are no notes in the spreadsheet, the field doesn't get populated and we get build errors
- Filtered out notes that were just empty spaces.
Fixes #906
=> chore: Fix empty notes, unset note values in CRDT dashboard

src/scss/global.scss
Turns off js-disabled menus in mobile.
Fixes #910
=> fix(design): Disable js-disabled on mobile

src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/__tests__/components/pages/state/__snapshots__/state-grade.js.snap, src/components/pages/state/state-grade.js
Changes link for state grades.
Fixes #919
=> chore: Change link for state grades

src/__tests__/components/pages/contact/__snapshots__/volunteer-form.js.snap, src/components/pages/contact/volunteer-form.js, src/components/pages/contact/volunteer-form.module.scss, src/components/pages/contact/volunteer-options.js
Description
Update availability language on volunteer form, point to new success page, fix field labels 
Related to #817 
Post-merge will need to publish new page titled "Thank you for wanting to volunteer" at /contact/volunteer-success
=> chore(docs): Update availability language on volunteer form etc.

.typo-ci.yml
=> Stop Typo CI messages about "lede"

src/components/pages/race/cta-links.js, src/pages/race/index.js
Updated published google sheet links to the current copies of the Race Data Entry sheet
=> fix(link): update google sheet links

src/pages/contact/volunteer.js
=> chore(volunteer): make title title cased

src/templates/blog-post.js
Enable featured image in blog posts.
=> chore: Enable featured image

src/__tests__/components/layout/__snapshots__/footer.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/components/layout/footer.js
Adds link to terms and conditions
Fixes #986
=> chore: Add link to T&C

.typo-ci.yml
Updated Typo CI file with words mentioned in the issue, 'nhpi' and 'aian'.
=> Update(Typo CI Ignore): included nhpi and aian

.github/PULL_REQUEST_TEMPLATE.md
=> chore: shorten PR template

src/__tests__/components/common/__snapshots__/summary-table.js.snap, src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/__tests__/components/pages/homepage/__snapshots__/latest-totals.js.snap, src/__tests__/components/pages/state/__snapshots__/state-history.js.snap, src/components/common/summary-table.js, src/components/pages/homepage/latest-totals.js, src/components/pages/state/state-history.js, src/pages/data/index.js
- Clarifies that positive is cases, not necessarily positive cases
- Fixes #997
=> Clarify case terminology

src/components/layout/header/search-autocomplete.js, src/components/layout/header/search.js
=> Make search button toggle

src/components/pages/homepage/datasets.js, src/components/pages/homepage/large-dataset.js, src/components/pages/homepage/large-project.js, src/components/pages/race/header-hero.js
Fixes #1018 
- Didn't use that threshold option that @kevee described.
- I only did the first 5 of the images and used colors used within the images.
Couldn't find ` src/pages/about-data/visualization-guide/index.js:299`
It was hard to view changes in my local environment so sorry if it doesn't look too good. Let me know what you guys think.
=> TraceSVG color change Proposal

README.md
Quick readme update to link to contributing page
=> docs: link to contributing guide on readme

src/components/search/search-no-results.js
=> chore: Update no-result content

.github/workflows/danger.yml, dangerfile.js, package-lock.json, package.json, src/stories/1-docs/3-Styling.stories.mdx
Fixes #1016 
- Added dangerfile to report on not using style mixins
- Added a Github workflow on pull request
=> feat(dev): Add danger to enforce style changes

src/components/layout/header/header.module.scss, src/components/layout/header/search-autocomplete.js, src/components/layout/header/search.js, src/context/search-context.js
Fixes issue #1034 (Search bar won't close)
=> fix(nav): Fixes bug where clicking search button did not close search bar

src/components/charts/bar-chart.js, src/components/pages/state/charts/charts.module.scss, src/components/pages/state/charts/index.js, src/pages/about-data/visualization-guide/_UsDailyDeathsContainer.js, src/templates/state.js
- made some small improvements to the BarChat component
- added bar charts for test, positive & death increase metrics to each state page.
some things to be done:
=> feat(state-charts): update bar chart component & add prelim charts to state data pages.

src/__tests__/components/layout/__snapshots__/header.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/components/layout/header/header.module.scss, src/components/layout/header/index.js, src/components/layout/header/mobile-menu.js, src/components/layout/header/search-autocomplete.js, src/components/layout/header/search-button.js, src/components/layout/header/search.js
- Fixes issue #1057 (Nav search input closes when 'SEARCH' label clicked)
- Fixes issue #1058 (Clicking away from window should close nav search bar)
=> Bugfixes: nav bar 'SEARCH' click and away from window click

src/components/pages/race/header-hero.module.scss
=> fix(race): hero color to match header

src/components/charts/bar-chart.js, src/components/pages/state/charts/index.js, src/pages/data/index.js, src/templates/state.js
- added Charts to main data page (because I like it) - we will want to
reorganize the component if we decide to stick with this
- added 7 day rolling average to the bar charts
- fixed a couple bugs in dailyAvg function
- added hospitalization data where available.
- added titles
=> feat(state-data): Add optional line to Bar Graph (avg)

src/__tests__/components/pages/homepage/__snapshots__/header-hero.js.snap, src/components/pages/homepage/header-hero.js, src/components/pages/homepage/header-hero.module.scss
Brings the homepage hero element in line with the landing-page container.
=> fix: Homepage hero alignment

src/__tests__/components/common/__snapshots__/summary-table.js.snap, src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/components/common/summary-table.js, src/components/pages/data/state-data.js, src/pages/data/index.js, src/templates/state.js
=> Fix summary table times

README.md
=> Add links to our hosted storybook

src/__tests__/components/pages/blog/__snapshots__/author-footer.js.snap, src/components/pages/blog/author-footer.js, src/components/pages/blog/author-footer.module.scss
=> Refine blog author footer styles

.github/workflows/sync-contentful-preview.yml
=> chore: Add skip netlify to PR title

.github/workflows/automerge.yml
Adds support to [automerge PRs](https://github.com/pascalgn/automerge-action) once checks are complete.
=> chore: Add automerge action

src/__tests__/components/common/__snapshots__/container.js.snap, src/__tests__/components/common/container.js, src/components/common/container.js, src/components/common/container.module.scss, src/components/layout/index.js
=> Add centered prop to layout, container

src/components/pages/race/cta-links.js, src/pages/race/index.js
Updated link to the spreadsheet page for the public CSV for CRDT (with simplified header rows for easier import)
=> chore(url): updated link to CRDT csv

src/components/common/social-sharing.js, src/components/common/social-sharing.module.scss, src/components/pages/blog/blog-lede.module.scss
=> chore: first pass with link copy behavior

src/__tests__/components/pages/homepage/__snapshots__/blog-list.js.snap, src/components/pages/homepage/blog-list.js, src/components/pages/homepage/blog-list.module.scss
=> chore(blog-list): fix broken byline author format

src/components/pages/blog/byline.module.scss
=> fix(byline): hide on mobile viewports

src/templates/blog-page.js
Closes #1189 
It looks like the categories got lost in a merge -- now they'll be back!
=> fix: add lost blog categories, spacing

src/components/common/volunteers-list.js, src/components/common/volunteers-list.module.scss
About page alignment for all the contributors
=> fix: about page alignment in viewport-ms

src/components/pages/blog/blog-content.js, src/components/pages/blog/blog-content.module.scss, src/components/pages/blog/blog-pagination.module.scss
Adds support for markdown content blocks in blog posts
=> feat: Add support for markdown content blocks

src/components/pages/blog/blog-teaser-list.js, src/components/pages/blog/blog-teaser-list.module.scss, src/components/pages/blog/categories.js, src/components/pages/blog/categories.module.scss, src/templates/blog-page.js
=> feat(blog-teaser-list): add categories above blog items

src/__tests__/components/common/__snapshots__/infobox.js.snap, src/components/common/infobox.js, src/components/utils/format.js
=> feat(infobox): add date to last updated time

plugins/gatsby-transformer-covid-census/gatsby-node.js, src/components/charts/bar-chart.js, src/components/common/summary-charts.js
Here's what it looks like with a single day of data:
=> Exempt FL from data requirements on hospitalization Chart

src/components/common/summary-charts.js, src/components/common/summary-charts.module.scss
=> chore(summary-charts): fix notes alignment

src/components/common/summary-charts.js
=> fix: update last date cutoff on summary chart to be the 15th

src/__tests__/components/common/__snapshots__/infobox.js.snap, src/components/common/infobox.js
=> fix(infobox): date format

src/components/layout/header/navigation.module.scss
=> feat(navigation): add subnav outline

src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/components/pages/data/state-data.js, src/components/pages/state/state-notes.js
Highlights date in the notes field to improve readability:
=> Highlight state notes dates

src/components/layout/header/header.module.scss
=> fix(header): use dark-bg return link styles

src/components/pages/blog/blog-pagination.js, src/components/pages/blog/blog-pagination.module.scss
Adds a little more polish to @tiagofsanchez's work on the blog pagination component.
Fixes #1276
=> fix(blog-pagination): design

src/__tests__/components/pages/blog/__snapshots__/related-posts.js.snap, src/components/pages/blog/blog-extras.js, src/components/pages/blog/related-posts.js, src/templates/blog-post.js
=> fix(related-posts): include published and updated dates in byline

src/components/pages/data/api/change-log.js, src/components/pages/data/api/change-log.module.scss, src/pages/data/api.js
- Adds a [Link to our API change log](https://headwayapp.co/the-covid-tracking-project-api-changes)
- Adds a Headway widget next to the link to indicate if there are new announcements
=> feat(api): Add changelog to API page

src/templates/blog-category.js
=> chore(design): fix the blog header layout

src/components/layout/header/return-link.module.scss, src/components/pages/race/dashboard/preamble.js, src/components/pages/race/dashboard/preamble.module.scss, src/pages/race/dashboard.js
- Reduce the line height and font size of the CRDT dashboard header on small devices
- Remove L/R return link padding
Fixes #1314
=> CRDT dashboard header + return link formatting fixes

src/pages/contact/index.js
=> Fixes #1324 adds Long-Term Care to contact form

src/components/charts/bar-chart.js
=> fix(charts): Fixed chart x-axis crowding

package-lock.json, package.json, src/components/pages/race/get-better-data/advocacy-form.js, src/components/pages/race/get-better-data/state-script.js, src/pages/race/get-better-data.js
=> feat(state-script): support templating for race + ethnicity data stats 

src/components/pages/blog/blog-categories-list.js, src/components/pages/blog/blog-categories-list.module.scss
=> fix(blog-categories): category spacing

netlify.toml, static/_redirects
=> API CORS Redirects

src/__tests__/components/pages/blog/__snapshots__/blog-lede.js.snap, src/__tests__/components/pages/data/__snapshots__/state-data.js.snap, src/__tests__/components/pages/data/__snapshots__/state-list.js.snap, src/__tests__/components/pages/state/__snapshots__/state-links.js.snap, src/components/common/social-sharing.js, src/components/common/state-nav.js, src/components/pages/data/state-data.js, src/components/pages/race/charts/index.js, src/components/pages/state/state-links.js
- Removes unused fathom goals
- Adds goal to track "Back to top" links
=> Clean up fathom goals

src/__tests__/components/layout/__snapshots__/sub-navigation.js.snap, src/components/layout/header/sub-navigation.js, src/components/layout/header/sub-navigation.module.scss
=> Subnav redesign for tablets/phones

gatsby-config.js, src/components/pages/blog/blog-categories-list.js
Offers env var switch to tun on contentful preview
=> feat: Switch between contentful preview and CDN

src/__tests__/components/pages/state/__snapshots__/state-notes.js.snap, src/__tests__/components/pages/state/state-notes.js, src/components/pages/state/state-notes.js
=> chore: Refactor date formatting tool

src/components/pages/data/ltc/download-links.js
- Adds new CSV links to the LTC downloads
=> chore: Add new dataset downloads

src/pages/contact/data.js
- Fix missing name on the data contact form.
=> chore: Fix name on date field

src/components/common/social-sharing.js, src/components/pages/blog/blog-hero.js, src/components/pages/blog/blog-lede.js, src/templates/blog-post.js
=> chore: Add twitter text field support

src/components/common/table-responsive.module.scss
=> fix(state-history): labels bleeding into data

src/pages/contact/index.js
=> chore(contact): remove CTAs

gatsby-config.js, gatsby-ssr.js, package-lock.json, package.json, src/components/common/recaptcha.js, src/pages/contact/data.js, src/pages/contact/other.js
=> chore: Add recaptcha to contact forms

dangerfile.js, gatsby-node.js, gatsby-ssr.js, src/components/common/statistic.js, src/components/common/tablet-disclosure.js, src/components/pages/race/dashboard/state-separate.js, src/components/pages/race/paragraph.js, src/components/search/search-result.js, src/pages/data/longtermcare.js
- Lints files missed from our linting config.
=> chore: Linting

src/components/common/social-sharing.module.scss
=> feat(social-sharing): update hover/focus styles

package-lock.json, src/components/pages/blog/blog-categories-list.module.scss
=> fix(blog-categories): remove double spacing

src/components/pages/about-data/visualization-guide/map-container.js, src/components/pages/about-data/visualization-guide/state-cumulative-tests.js, src/components/pages/about-data/visualization-guide/us-daily-deaths.js, src/components/pages/about-data/visualization-guide/us-total-positive-deaths.js
Fixed date formatting error in visualization guide.
=> fix: Date formatting for visualization guide

src/components/pages/blog/byline.js, src/components/pages/blog/byline.module.scss
=> feat(byline): handle more than three headshots

src/__tests__/components/charts/__snapshots__/bar-chart.js.snap, src/components/charts/bar-chart.js, src/components/charts/bar-chart.module.scss, src/pages/data/index.js, src/templates/state/index.js
- Uses a new `Chart annotation` Contentful type instead of using the `Event` content type
=> chore: Change annotations to Chart Annotation type

.circleci/config.yml, package-lock.json, package.json, src/components/pages/blog-features/scrollytelling/index.js, src/utilities/scrollama.js
=> chore: Remove scrollama placeholder in favor of null

src/__tests__/components/pages/blog/__snapshots__/related-posts.js.snap, src/components/pages/blog/footer/related-posts.js
Fixes #1467 by adding missing `/` to the blog link.
=> fix: Blog link in related posts

src/components/pages/contact/volunteer-form.js
=> Language changes to volunteer form to make it friendlier

src/__tests__/components/pages/data/__snapshots__/cards.js.snap, src/__tests__/components/pages/data/cards.js, src/components/pages/data/cards/cases-card.js, src/components/pages/data/summary.js, src/pages/data/index.js, src/templates/state/cases.js, src/templates/state/index.js
- Adds probable and confirmed cases to cases card
- Fixes #1394
=> feat: Add probable and confirmed cases

src/components/social-media-graphics/race/social-card.module.scss
=> fix(social-cards): enlarge logo image width

src/components/social-media-graphics/race/social-card.js, src/components/social-media-graphics/race/social-card.module.scss, src/components/social-media-graphics/race/utils.js
=> chore(social-cards): bump font size to 14px

src/components/pages/race/infection-and-mortality-data/select.js
=> fix(crdt-social-cards): handle lowercase state hashes

src/components/pages/race/header-hero.module.scss
=> fix(race): subnav items overlapping with builders image

src/components/common/press-list.module.scss
=> fix(race): press list sources

src/components/pages/race/infection-and-mortality-data/share.js, src/components/social-media-graphics/race/social-card.module.scss
=> CRDT social card fixes

README.md, package.json
Fixes #1522 
Description:
- Create a custom develop command to increase Node's memory allocation
- References the custom develop command within the README
=> dev: Added a custom develop command

package.json, src/components/pages/about-data/visualization-guide/charts/map.js, src/utilities/interpolators.js, yarn.lock
=> Fix choropleth color problem on Visualization Guide page

src/components/common/long-content.module.scss
Adds styling for inline `<code>` blocks
=> chore: Add code block support

src/components/pages/state/long-term-care/facilities.js, src/components/pages/state/long-term-care/overview.js, src/templates/state/long-term-care.js
=> fix: Use same numbers in card and page for LTC

src/components/pages/state/long-term-care/facilities.js, src/components/pages/state/long-term-care/facilities.module.scss, src/templates/state/long-term-care.js
=> chore: Add outbreak data to facilities

plugins/gatsby-source-covid-tracking-tweets/gatsby-node.js, src/components/pages/data/daily-tweet.js
Fixes #1556 by setting timezone on tweets
=> chore: Set timezone on tweets

src/components/pages/data/daily-tweet.js
=> fix: Remove console log

src/pages/blog/test-positivity.js, src/templates/blog-post.js
=> chore: Remove unused blog body field

src/__tests__/components/pages/data/__snapshots__/cards.js.snap, src/components/pages/data/cards/tests-national.js
With regard to -> Design: line spacing in national Tests & Cases cards #1564 from @amandafrench
=> fix(design): fixed the tests-card with the proper spacing

src/components/common/overview-wrapper.js, src/components/pages/state/preamble.js, src/components/pages/state/preamble.module.scss
=> chore: Add padding to preamble

src/templates/state/long-term-care.js
=> chore: Change to aggregate numbers

src/__tests__/components/common/__snapshots__/tweet.js.snap, src/components/common/state-nav.module.scss, src/components/common/tweet.js, src/components/pages/state/state-tweets.js, src/components/pages/state/state-tweets.module.scss, src/templates/state/index.js
=> Miscellaneous state tweet updates

src/components/pages/blog/footer/blog-extras.js, src/components/pages/blog/footer/download-links.js, src/components/pages/blog/footer/download-links.module.scss, src/templates/blog-post.js
- Adds download links to blog posts
=> chore: Add download links button to blog post

src/components/pages/blog/footer/download-links.js
=> chore: Fix apostrophe

src/components/pages/state/long-term-care/facilities.js, src/components/pages/state/long-term-care/facilities.module.scss, src/components/pages/state/long-term-care/preamble.js, src/templates/state/long-term-care.js
- Fixes #1620 
- Hides download facilities link if there are no facilities
=> feat: Link sharing for LTC facilities, fix 404 on facilities download

src/components/pages/contact/volunteer-form.js
Remove website from volunteer page
=> chore: Remove website team

src/components/layout/header/index.js, src/components/layout/header/thanksgiving-warning.js, src/components/layout/header/thanksgiving-warning.module.scss, src/components/layout/index.js, src/pages/data/index.js, src/templates/state/cases.js, src/templates/state/chart-tables.js, src/templates/state/hospitalization.js, src/templates/state/index.js, src/templates/state/outcomes.js, src/templates/state/tests-antibody.js, src/templates/state/tests-viral.js
- Adds warning about thanksgiving
=> chore: Add thanksgiving warning

src/components/layout/header/thanksgiving-warning.js
=> Change warning to past tense

src/__tests__/components/social-media-graphics/race/__snapshots__/header.js.snap, src/components/social-media-graphics/race/social-card.js, src/components/social-media-graphics/race/social-card.module.scss, src/components/social-media-graphics/race/utils.js
=> fix(crdt-social-cards): add hair space surrounding `/`

src/__tests__/components/pages/race/__snapshots__/cta-links.js.snap, src/__tests__/components/social-media-graphics/race/__snapshots__/header.js.snap, src/components/pages/race/cta-links.js, src/components/social-media-graphics/race/social-card.js, src/components/social-media-graphics/race/social-card.module.scss, src/components/social-media-graphics/race/utils.js
Update the CSV link from one google worksheet to another
We removed any sheets not for data entry from the data entry worksheet, to try to help with very slow responses during shifts
The data is now referenced from a new URL
=> chore(url): Updating the link for the CSV

src/components/pages/contact/volunteer-form.js
Want to find out if volunteers have experience with Slack.
=> chore: Add Slack experience prompts

src/components/pages/data/charts/map.js, src/pages/data/charts.js
Change formula for chart map to use positiveIncrease, and change steady to -10% to 10%
=> fix: Change to new positives for map

src/components/pages/blog/blog-content.js, src/components/pages/blog/content-blocks/image-content-block.js, src/components/pages/blog/content-blocks/image-content-block.module.scss, src/templates/blog-post.js
Add link to image in image block.
=> chore: Add image link

src/components/layout/header/data-warning.js, src/components/pages/data/cards/hospitalization-hhs-card.js
=> chore: Change HHS link

gatsby-config.js, src/components/pages/data/cards/hospitalization-hhs-card.js, src/pages/data/index.js, src/templates/state/index.js
- Change to new HHS hospitalization file
- Use new integer fields
=> chore: Change to new HHS file

src/components/pages/contact/volunteer-form.js
No need for volunteers in journalism and dataviz right now.
=> Removes dataviz and journalism options from volunteer form

src/components/pages/data/cards/small/small-card.module.scss
=> fix(small-cards): handle text overflow

.circleci/config.yml, .gitignore, gatsby-config.js, package.json, src/__tests__/components/pages/state/__snapshots__/state-links.js.snap, src/components/pages/data/states.js, src/components/pages/state/preamble.js, src/components/pages/state/state-links.js, src/pages/data/index.js, src/templates/state/index.js, yarn.lock
Use screenshot configs for YAML config
=> chore: Add screenshot YAML config

src/components/pages/race/dashboard/percentage-overview.js, src/components/pages/race/dashboard/percentage-overview.module.scss
=> Fix crdt dash percentage overview

src/components/pages/data/state-nav-wrapper.module.scss
=> fix(state-nav): align rule with header

src/pages/data/long-term-care/index.js
=> chore: Update LTC landing page charts

src/components/pages/homepage/visualization-gallery/components/sidebar.js
Fixed broken link in related blog post
=> chore: Fix related blog post link

src/data/navigation/header.yml
=> chore: Fix nav case

src/utilities/schema.js
=> chore: Add LTC facilities schema

gatsby-config.js
=> chore: Set google fonts to display-swap

src/components/pages/homepage/visualization-gallery/components/sidebar.js, src/components/pages/homepage/visualization-gallery/index.js, src/components/pages/homepage/visualization-gallery/items/us-map/index.js, src/components/pages/homepage/visualization-gallery/items/us-map/metrics.js, src/components/pages/homepage/visualization-gallery/items/us-map/us-map.module.scss, src/pages/homepage-visualizations.js
- Adds hospitalization map
- Sample viz page
=> chore: Add hospitalization map

gatsby-config.js, gatsby-node.js, package.json, src/__tests__/components/layout/__snapshots__/footer.js.snap, src/__tests__/components/layout/__snapshots__/index.js.snap, src/components/layout/footer.js, src/components/layout/footer.module.scss, src/pages/about/sitemap.js, static/robots.txt, yarn.lock
- Adds canonical tags to pages
- Makes generated redirects permanent
- Adds an HTML sitemap
- Links to sitemap from footer
- Adds `robots.txt` with link to XML sitemap
- Fixes #1671
=> chore: SEO fixes

src/components/common/detail-text.module.scss
=> chore(crdt-sources): make details one line

src/__tests__/components/pages/data/__snapshots__/cards.js.snap, src/components/pages/data/cards/outcomes-card.js
=> chore: Remove recovered note from national card

src/components/pages/data/hhs-facilities/facility-details.js, src/components/pages/data/hhs-facilities/map/infobox.js
=> feat: Add total bed usage to HHS map

src/components/pages/data/hhs-facilities/map/infobox.js
=> chore: Remove duplicate colon

src/templates/state/notes.js
=> chore: Add dateModified to preamble

src/components/pages/homepage/visualization-gallery/items/us-map/grid.js, src/components/pages/homepage/visualization-gallery/items/us-map/index.js, src/components/pages/homepage/visualization-gallery/items/us-map/metrics.js, src/components/pages/homepage/visualization-gallery/items/us-map/sidebar.js, src/components/pages/homepage/visualization-gallery/items/us-map/states.js, src/components/pages/homepage/visualization-gallery/items/us-map/us-map.module.scss, src/pages/homepage-visualizations.js
=> feat: Add new 7 day change in deaths map for homepage

src/components/pages/blog/blog-content.js
=> chore: Fix source of fixed-width images

src/components/pages/data/hhs-facilities/facility-details.js, src/components/pages/data/hhs-facilities/map/infobox.js
Revert broken facility details
=> chore: Revert facility details

src/components/pages/data/hhs-facilities/map/infobox.js
=> chore: Fix duplicate colons

src/components/pages/data/hhs-facilities/anomalies.js, src/components/pages/data/hhs-facilities/definitions.js, src/components/pages/data/hhs-facilities/definitions.module.scss, src/components/pages/data/hhs-facilities/facility-details.js, src/components/pages/data/hhs-facilities/facility-details.module.scss, src/components/pages/data/hhs-facilities/map/infobox.js, src/components/pages/data/hhs-facilities/map/infobox.module.scss, src/components/pages/data/hhs-facilities/map/legend.js, src/components/pages/data/hhs-facilities/map/legend.module.scss, src/components/pages/data/hhs-facilities/search.js, src/pages/data/hospital-facilities/anomalies.js, src/pages/data/hospital-facilities/index.js, src/pages/data/hospital-facilities/search.js
- Adds page to highlight hidden HHS facilities
=> chore: Add anomalies page

src/context/search-context.js
=> chore: Fix notes in search results

src/components/pages/data/hhs-facilities/facility-details.js, src/components/pages/data/hhs-facilities/map/infobox.js
=> chore: Fix short circuited logic in infobox

src/pages/contact/data.js
=> Remove Recovery data field from data issue form

src/pages/contact/other.js
=> Adds optional URL field to contact form and tweaks language

src/components/pages/about-data/visualization-guide/index.js
=> Remove outdated denominator section of viz guide

src/components/pages/blog/blog-content.js, src/templates/blog-post.js
=> chore: Add mobile height to tableau block

src/pages/about/track-impact/index.js, src/pages/about/track-impact/success.js
=> feat: Add impact form

src/components/pages/data/hhs-facilities/anomalies.js
=> chore: Fix string comparison for anomalies

src/components/pages/state/state-grade.js
=> chore: Rename data reporting section

src/pages/about-data/state-reporting-assessments.js
Adds landing page for all state reporting assessments
=> chore: Add landing page

src/components/pages/data/summary.js, src/templates/state/long-term-care/index.js, src/templates/state/notes.js, src/utilities/csv.js
=> chore: Remove data quality grade

src/components/pages/data/cards/crdt/create-race-data.js
=> chore(crdt): reorder race/ethnicity cards

src/components/layout/header/index.js, src/components/pages/state/preamble.js
=> chore: Add CSV link

src/components/social-media-graphics/race/social-card.module.scss
=> fix(crdt): use updated colors for social cards

src/components/pages/data/hhs-facilities/map/index.js
Fixes HHS legend update on layer change
=> chore: Fix hhs legend

src/__tests__/components/pages/race/__snapshots__/national-chart.js.snap, src/components/pages/data/cards/crdt/create-race-data.js, src/components/pages/race/national-chart.js, src/components/pages/state/race-ethnicity/chart-section.js
* national chart
* crdt cards
* crdt historical charts
=> chore(crdt): update 'Alaskan' -> 'Alaska'

src/components/pages/homepage/blog-list.js
=> chore: Bump the limit of blog lists

src/components/pages/state/long-term-care/preamble.js, src/components/pages/state/long-term-care/preamble.module.scss, src/templates/state/long-term-care/index.js
=> chore: Add assessment label to LTC preamble

src/components/pages/data/api/explorer-2.js
- Changes references of v2beta to v2
=> chore: Change to v2

src/components/pages/data/cards/hhs-tests-viral.js
=> chore: Fix link to HHS data

src/components/social-media-graphics/race/social-card.js
Pass stateStatus to the ChartRow elements
=> fix: crdt social cards

src/templates/state/index.js
=> chore: Remove unset Link

src/components/layout/header/index.js, src/components/layout/index.js, src/pages/data/api/index.js, src/pages/data/api/version-2.js, src/pages/data/charts.js, src/pages/data/download.js, src/pages/data/hospital-facilities/anomalies.js, src/pages/data/hospital-facilities/index.js, src/pages/data/hospital-facilities/search.js, src/pages/data/index.js, src/templates/state/assessment.js, src/templates/state/cases.js, src/templates/state/chart-tables.js, src/templates/state/hospitalization.js, src/templates/state/index.js, src/templates/state/notes.js, src/templates/state/outcomes.js, src/templates/state/race-ethnicity.js, src/templates/state/tests-antibody.js, src/templates/state/tests-antigen.js, src/templates/state/tests-viral.js
=> feat: Use warning on every page

src/components/pages/about-data/data-summary.js, src/components/pages/about-data/data-summary.module.scss
- Some design improvements to the datasets page
=> chore: Add TOC, line under categories

src/components/charts/tableau.js, src/components/charts/tableau.module.scss
=> chore: Add tableau warning

src/components/pages/data/long-term-care/map/index.js, src/components/pages/data/long-term-care/map/infobox.js, src/components/pages/data/long-term-care/map/legend.js
=> feature: Use fallback geocoded city/county in LTC map

src/components/layout/header/index.js, src/components/pages/homepage/impact.js
=> chore: Remove warning box

src/components/pages/homepage/about.js, src/components/pages/homepage/impact.js
=> chore: typo and linting of homepage

static/_redirects
=> chore: Add tilde redirect

src/components/pages/homepage/about.js
=> chore: Update hero about text

src/__tests__/components/pages/race/__snapshots__/cta-links.js.snap, src/components/pages/blog/blog-content.module.scss, src/components/pages/data/state-data.js, src/components/pages/race/cta-links.js
- Removes fathom goals
- Fixes blog `<blockquote>` style to remove quotes and make text same color
=> fix: Blockquote style, fathom goals

src/components/common/impact-form.js, src/components/pages/blog/blog-content.js, src/pages/about/track-impact/index.js, src/templates/blog-post.js
- Adds "Impact Form" content block
=> chore: Add impact form block

src/components/pages/data/long-term-care/download-links.js
=> chore: Change link to download state notes

src/components/pages/homepage/impact.js
- Update impact statements on the homepage
=> chore: Update impact statement

src/components/pages/homepage/impact.js
=> chore: Fix JAMA typo

src/components/pages/blog/blog-content.module.scss
Adds style for pre tag in posts
=> chore: Update style for pre tag

src/components/pages/blog/blog-categories.js, src/components/pages/blog/blog-hero.js
=> chore: Fix categories list

src/components/pages/blog/blog-content.module.scss
=> chore: Add margin to only multiple-margin blockquotes

src/components/pages/state/long-term-care/summary-table.js
Change definition of LTC lumped categories
=> chore: Change lumped definitions
