- .eleventy.js
- _src/_assets/css/_states.scss
- _src/_templates/states.njk
- package.json
This allows us to pass any data—in this case, state notes pulledin via the remote JSON files—through a Markdown parser to render it as expected at the template level.
Note that this will require folks to re-run `npm install` once merged.
> Add custom `markdownify` filter

- .eleventy.js
- _src/_assets/css/_layout.scss
- _src/_assets/css/_states.scss
- package-lock.json
Did a quick tightening-up on yesterday’s states page work (#13):
- Pulled the Twitter icon closer to the state name, so that these tables don’t look like things Twitter generated. Because they are not.
- Refactored the table styles a bit (https://github.com/COVID19Tracking/website/commit/38769b3c3340b6d97006a80278824d703da8126d#diff-21411f591eb93a949eb6f1f8fd79ad70R104) so there’s a common `table` component that’s centrally accessible. (@webmasterkai, I think your summary table still looks 💖great💖, but please let me know if I donked anything up.)
- Bumped up the size on the `.updates` block, just to make it look a little more…page level-y yes this is a word now
Here’s a before & after GIF!
Would love to hear folks’ thoughts.
In addition to the above, I tweaked the BrowserSync config _very …
> Slight tweaks to states page

- _src/api.md
Appending any of the detail routes to that sample did not work.
For example, this link does not work: https://covid.cape.io/api/states
Maybe this is better handled via the CMS, maybe I should have just made an issue.
> documentation had a what seemed like an old route in the example. 

- README.md
Probably we eventually want to make `npm run dev` work correctly without
requiring `npm run prod` first, but this seems like an OK stopgap until then.
> [README] Update the instructions to include step about `npm run prod`

- .eslintrc.js
- .prettierrc.js
- README.md
- package-lock.json
- package.json
Setting up ESLint and Prettier for this repo
At @webmasterkai's suggestion, we are mostly using the Airbnb JS Style guide
except tweaking it to use semicolons as little as possible.
I set this up using this script: https://github.com/paulolramos/eslint-prettier-airbnb-react in the hopes that it would make sure that eslint and prettier
would play nicely together. I manually edited the configuration
files (`.pretterrc.js` and `.eslintrc.js`) to set semi to never/false.
I didn't run prettier or ESLint autofix over all the files in the repository
as part of this change. That could be done as separate commit if someone
wants to do it.
I also didn't setup any commit hooks or other enforcement mechanisms for
these policies. If these seem to be working well and we want to enforce
them more …
> Configuring eslint and prettier

- .eleventy.js
- _src/_templates/us-daily.njk
This makes the dates more readable and more consistent with other dates
on the site.
I also included the 3 letter abbrev for day of the week at the end of the
date since I think that is what I would want to see (weekends are sometimes
anomalous, sometimes easier to think in terms of days of the week when
thinking about the recent past)
This can be changed by adjusting the format string here:
+      return DateTime.fromFormat(dayStr + '', 'yyyyMMdd').toFormat(
+        'dd LLL yyyy ccc',
Taking out the ` ccc` will remove the day of the week
New look is this:
> [US Daily Data] Fix date formatting

- .editorconfig
If we’re going to start taking in more external contributions (à la https://github.com/COVID19Tracking/website/pull/43), it’d be great to have an [.editorconfig](https://editorconfig.org/) that documents a few of our expectations around (just e.g.) whitespace.
…so that’s what this PR is offering hi
This is definitely a draft, so comments/feedback are welcome. And this can definitely evolve! Treating this as a starting point more than anything.
> Adding in a .editorconfig

- _src/api.md
I tried to open the CSV API link http://covidtracking.com/api/states/daily.csv  from https://covidtracking.com/api/
with curl and it failed with a redirect.
They should all be `https` links I think, to fix my use case (which is easily fixed by most  curl users manually) but also to protect the requests from heaven knows what....
> Switch to https URLs for security, function

- _src/_assets/css/_button.scss
- _src/_assets/css/_globals.scss
- _src/_assets/css/_header.scss
- _src/_assets/css/_layout.scss
- _src/_assets/css/_states.scss
- _src/_assets/css/_tables.scss
- _src/_assets/css/_usDaily.scss
- _src/_assets/css/_variables.scss
- _src/_assets/css/all.scss
- _src/_templates/base.njk
- _src/_templates/partials/header.njk
- _src/_templates/us-daily.njk
- _src/index.md
After a [request from Julie](https://twitter.com/joulee/status/1239755367556337665?s=20) for some design/CSS feedback, I volunteered some time to check out the project and see where I could be of use. Holled at @ccheever as well to get a brief lowdown on things. This PR is very open to any and all feedback, or outright closure if y'all aren't into it :). Just holler with any questions or comments.
Below is a summary of changes and some screenshots. My changes largely focused on under the hood updates, optimizing CSS, removing duplicated code, some minor Markdown changes, and adding clear navigation. Hope it helps!
Anyway, here we go!
- Updated links to have clear blue color throughout. As I understand it, the goal is to keep things black and white, but the links didn't seem that easily …
> Refactor CSS and design iterations

- _src/_assets/css/_button.scss
- _src/_assets/css/_globals.scss
- _src/_assets/css/_header.scss
- _src/_assets/css/_variables.scss
- _src/_templates/base.njk
- _src/_templates/partials/footer.njk
- _src/_templates/partials/header.njk
Here’re a few small design updates to address items in #63:
- Updated colors, per Júlia’s spec. (Note: I _very slightly_ adjusted a few to make sure they pass WCAG contrast thresholds. Would love to hear how folks like them!)
- Removed the underlines on the links in the primary navigation.
- Also added an `active page` state, to match the work @Wilto did in the footer.
Opening this for review/discussion!
> Updated colors for links & buttons (per #63); active page indicator

- _src/_templates/state.njk
Currently the state notes are rendered as text, not as markdown:
This PR should fix that.
> markdownify state notes

- README.md
- package.json
grunt can be run before grunt watch to compile assets once before watching
so there's no need for control+c shenanigans I believe.
I also simplified the instructions considering how simple the setup process
is, although it does assume you have npm and node installed.
> Simplify development setup and instructions

- _src/_templates/state.njk
- _src/_templates/us-daily.njk
- _src/data.md
This PR fixes some minor issues when I did an accessibility audit:
Also, this came up, but I think is fixed on #73
> Minor accessibility tweaks

- _src/_templates/states.njk
- _src/_templates/us-daily.njk
We don't actually "update" any data when we refresh/pull from the API. Which means
the timestamp listed falsly suggest we update the data show on the States and
US Daily pages when `sheets.updated` changes.
I think "refresh" avoids that potentially confusing term but it does leave
some ambiguity which I think could either be solved with copy on the page or
using an info tooltip for people who care what "Last refreshed" means exactly.
By contrast, the `Last updated` we show for each state *is in fact* when that state last updated their data according to timestamps we report back. So I think it's important to distinguish these two uses of the term.
> Differentiate Last updated from Last refreshed

- _src/_templates/states.njk
currently this isn't loading the state's name -- see #73
> stateName --> name

- _src/_assets/css/_globals.scss
- _src/_assets/css/_layout.scss
Per #82, here are a couple small adjustments to our lists!
- We were removing the default margins on all lists, numbered (`ol`) and bulleted (`ul`). Now, we’re _only_ removing margins on lists that have classes attached to them. (https://github.com/COVID19Tracking/website/commit/a8b801341415fcdc7fc96c6fb4251f3519299917#diff-e0f67e5f919e01d7ea1925d34ba25159R12) That should re-outdent the bullets, per the request!
- I’ve tightened up the bottom margin on `li` elements.
> List tweaks! (closes #82)

- _src/_templates/state.njk
- _src/_templates/states.njk
This adds the last checked time adjacent to the last updated time in table captions.
This also closes #74 
See below for the updated appearance:
> Add "Last Checked" Time to Tables (close #74)

- _src/_templates/base.njk
Before: 
After:
Importantly doesn't mess with the homepage or any page that doesn't have a `title` in its front-matter:
Fixes #86
> Include current page title in <title> when available

- _src/_templates/state.njk
- _src/_templates/states.njk
This handles missing grades by labeling the grade as "N/A" if it is not available.
----
Current (states page):
Updated (states page):
----
Current (state page):
Updated (state page):
> Handle missing grades

- _src/__tests__/api.js
- _src/__tests__/build.js
- package-lock.json
- package.json
This adds two new steps to the build process (also available as npm scripts):
`test-api` - Checks that the API endpoints are up, are returning valid JSON, and objects match expected values.
`test-build` - Checks that homepage, data page, and individual state pages are built.
These were added to the `prod` script to make sure everything is OK before netlify publishes.
> Added Jest tests for API, build steps

- _src/about-tracker.md
I don't think there is a way to do this in MD, so I ended up using HTML here, with inline styles (not great, I know).
See #94 -- this table currently takes up a lot of space.
Here's the updated version:
I won't merge this yet since I want someone else to be on board with this implementation of an HTML table in the middle of this Markdown file. If anyone has a cleaner way to achieve this, I am all ears.
> shrink table width

- .eleventy.js
Julia reports website is displaying screenshot times in UTC instead of ET.
> add timezone to screenshot date

- _src/_templates/states.njk
history is lower down now, top to bottom: current data source, history, data quality
> re-order state-notes

- _src/_templates/index.njk
- _src/index.md
This reverts commit aa5ae1fd195fdb13426b9989fc9f6f0d89233022.
This re-adds the add-press-links PR, now that the spreadsheet has been cleaned up.
> Re-add press links. Spreadsheet no longer has bad links.

- _src/_assets/css/_pressLogos.scss
Press logos now wrap on mobile, instead of extending in the x direction out of the viewport.
This closes 1/5th of #101
> Flex press logos (closes #155)

- .github/budget.json
- .github/lighthouserc.json
- .github/workflows/lighthouse.yml
Adds an action to do a Lighthouse audit using [treosh/lighthouse-ci-action](treosh/lighthouse-ci-action). This PR also includes a `budget.json` file to define [page size budgets](https://web.dev/use-lighthouse-for-performance-budgets/). 
I'm including this so we can start getting baseline performance audits. We can refine budgets and pass/fail assertions like first paint for critical paths in the future.
> Add lighthouse audit to PRs

- _src/_assets/css/_header.scss
Fixes #101 (I think this is the last one)
Takes padding and margin down for mobile to prevent wrapping
> Shrink padding for header in mobile

- src/components/common/press.js
- src/pages/data/index.js
- src/stories/12-Press-links.stories.js
Add component for press links
*Note that this isn't rendered anywhere yet. This can be put wherever the design people want it to end up.*
GraphQL Query:
```graphql
allCovidPress(filter: {addToCovidTrackingProjectWebsite: {eq: true}}) {
edges {
node {
title
url
publishDate(formatString: "DD MMMM YYYY")
id
publication
}
}
}
```
> Add component for press links

- _src/_assets/js/dashboard-charts.js
- _src/dashboard.md
This adds horizontal bar charts for deaths by states
- sorted descending
- no horizontal lines
Open questions
- currently using dummy placeholder text, need summary
- How should I handle "null" deaths? In this PR I filtered them out and did not note this anywhere on the UI
> [add] added horizontal bar charts for deaths by state

- package-lock.json
- package.json
- src/components/common/disclosure.js
- src/scss/components/common/disclosure.scss
- src/stories/12-Disclosure.stories.js
Added a 'disclosure' component using [ReachUI](https://reacttraining.com/reach-ui/disclosure). This is useful for hiding elements like glossaries, etc. that we don't want default-expanded.
Preview: https://5e7e043142dad500085645dc--goofy-tesla-43452a.netlify.com/__storybook/?path=/story/disclosure--disclosure
> Added disclosure component

- gatsby-node.js
- package.json
- src/templates/state.js
Use an objecthash for the screenshot GraphQL hash, instead of the ETag from the API.
> fix(code): Don't use Etags from screenshots

- _src/_assets/css/_charts.scss
- _src/_assets/js/dashboard-charts.js
- _src/dashboard.md
1. Removed legends from the two following bar charts:
- TOTAL CUMULATIVE DEATHS BY DAY IN THE US
- TOTAL DEATHS BY STATE
2. Added logic to expand and collapse bar charts
> feature(dashboard): added expand/collapse to horizontal bar chart; removed legends from death charts

- .github/workflows/lighthouse.yml
Only run the lighthouse github action in the 'master' branch PR deploys
> chore(git): Lighthouse only on master branch

- gatsby-config.js
Made the development warning not show for `gatsbyjs` branch
> chore: Turn off dev warning for deploy #244

- README.md
- gatsby-config.js
Very tiny change to make environment variables a bit easier to set with dotenv. (Figured first PR should be small!)
> feat(site): Tiny tweak to use dotenv

- gatsby-config.js
I updated the hostname of the API so we are hitting the backend API endpoint, that way we aren't referencing in case a build goes haywire.
> chore: Change API endpoints

- src/components/pages/homepage/visualizations.js
- src/scss/components/header.scss
- src/scss/components/hero.scss
- src/scss/global.scss
Added in a fix for the button hover styles bug that @jasonsantamaria flagged in https://github.com/COVID19Tracking/website/issues/276#issuecomment-606982973; also added a focus style for each `:hover` rule in our css, and introduced [a base `:focus` style for keyboard users](https://github.com/COVID19Tracking/website/pull/307/commits/8e9c4f484f54daeff34b9e41666d439f9f760977#diff-086adca9968d5685b874aa4d44a3c61cR38-R40).
(Also fixed a smol copy tweak on the homepage: https://github.com/COVID19Tracking/website/pull/307/commits/eccc3029fd0c15e60370ac21ad36d470d8ebc054)
> Fix for header button text bug; focus styles

- src/scss/components/common/infobox.scss
> fix(design): align infobox sync icon with infobox header

- netlify.toml
- package.json
For some reason netlify is not caching `/build/node_modules` correctly - so we are making them install every time until we get this fixed.
> fix: Force install build packages (temp fix)

- .env.example
- README.md
Let's not list environment variables in the README when we can put that all in
a single place and let's not encourage people to use bash profile for environment
variable management when we have dotenv in the dependencies taking care of that
for us.
I've simplified the installation instructions accordingly but eventually I
think the `cp` operation could be covered by a setup script. I'm just not
super familar with external npm setup scripts, I'd want it to be a bash
script that outputs some feedback, not something that just copies the
`.env.example` file and leaves it in a broken state without any feedback.
> Simplify Gatsby setup in README

- .npmrc
- package.json
`gatsby develop` errors with any Node version earlier than 10.13, so I’ve added this
requirement to the package.json and set an .npmrc file to require it when `npm install`
is run.
My next step would be to define an `.nvmrc` to enable auto-switching to 10.13 but that’s
assuming:
- people use nvm
- we’re okay tracking the minimum node version in two places: `package.json` and `.nvmrc`
Let me know and I’ll update this PR.
> Document required Node version

- package.json
Chain build commands with `&&` to throw an error on any command.
> fix: Error out on any build error

- src/data/navigation/header.yml
- src/templates/state.js
Filtered out "secondary" screenshots from the state page.
> fix: Remove duplicate screenshots from state page

- src/components/pages/data/state-data.js
- src/components/pages/data/state-list.js
- src/components/pages/data/state-nav.js
- src/components/pages/state/screenshots.js
- src/components/pages/state/state-history.js
- src/components/pages/state/state-links.js
- src/pages/data/index.js
- src/scss/components/pages/data/state-data.scss
- src/templates/state.js
Two files:
* `src/pages/data/index.js`
* `src/templates/state.js`
had many React components in them. This PR breaks the components in each original file into separate files located in the `src/components/pages/` directory.
This should increase the readability and accessibility of the codebase.
This will likely cause some merging issues as other PRs crop up -- merging sooner would hopefully mitigate those.
> Move React components to separate files

- gatsby-config.js
- package-lock.json
- package.json
When navigating using the site tabs/UI, the URLs do not have trailing slashes, which ensures the Gatsby `Link` components render with correct aria-current attributes and selected states. The current page's tab is highlighted.
However, if you directly navigate with a trailing slash, such as:
[https://covidtracking.com/data/](https://covidtracking.com/data/)
The `Link` matching logic fails. Adding the [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/) plugin fixes the issue, but only works in production mode.
To test locally, run `gatsby build` and serve the /public directory using local static file server.
> Fix active tab state when URL has trailing slash

- netlify.toml
- static/_redirects
Added API redirects to the new "V1" prefixed API.
Added CORS header
Fixes #386 
Fixes #384
> API redirects & CORS

- src/components/common/summary-table.js
- src/pages/data/index.js
- src/pages/data/us-daily.js
Alexis put this out to the website team earlier today:
> Because some states report current and some states report cumulative hospitalization/ICU numbers, we a fundamental mismatch in what these data represent. We can't just push currents across into cumulatives to get a cumulative number [...] The only real answer, I think, is to not provide a national summary of outcomes data.
This PR **does** remove the outcomes data from the US summary table
This PR **does not** remove the outcomes data from individual states (it is retained on both the data index, under each state and on the individual state pages)
[Relevant Slack thread](https://covid-tracking.slack.com/archives/CUYAS1M25/p1586199198317900)
We'll need to update the contentful snippet (`dataSummaryFootnote`) for this update as well …
> Remove US total outcomes data

- .github/workflows/main.yml
This PR changes our Github Action to use a new Github Secret, `NETLIFY_BUILD_HOOK`
This will help prevent forks from also building the website. Fixes #324
> fix: Use github secret for webhook, 1 per hour

- src/pages/404.js
Fixes #312 
Uses content from a snippet in Contentful so content editors can manage the text of the Page-not-found page. 
[Preview here](https://deploy-preview-405--upbeat-lovelace-3e9fff.netlify.com/lkjsdf)
I added the following to the snippet:
> Looks like we couldn't find that page. Here's a few helpful places to find what you're looking for:
> 
> - [State-by-state Data](/data) - A list of COVID data by state
> - [US Daily totals](/data/us-daily) - A list of US COVID totals by day
> - [FAQ](/about-data/faq) - FAQ about our data and process
> - [Data API](/api) - Our data API for developers
> 
> Think you found a bug with the website? [Reach out on GitHub](https://github.com/COVID19Tracking/website)
> feat: Use snippet for 404 page

- src/scss/components/common/container.scss
Fixes #320 
Because we had a hard-width of 1140px on the container, which is larger than our lg viewport, there was a gutter missing.
This makes 1140 the width beyond the XL viewport, and 1000 the max-width for all others.
> fix: Container padding between xl and lg viewport

- package-lock.json
- src/pages/dashboard/_MapContainer.js
- src/pages/dashboard/_SmallMultiplesAreaCharts.js
- src/pages/dashboard/_UsAreaChartContainer.js
- src/pages/dashboard/charts/_AreaChart.js
- src/pages/dashboard/index.js
first PR converting a chart to using Gatsby data instead of fetching from API.
You can see how much faster the top chart loads than everything below.
For using graphql queries within a component (instead of a page) you must use a `<StaticQuery>` component.  More info can be found [here](https://www.gatsbyjs.org/docs/static-query/).
@kevee would like you to take a look and make sure we've got your vote of confidence before converting the rest of the dashboard using this pattern.
> converted US Area chart to use Gatsby data

- src/pages/dashboard/charts/_Map.js
- src/pages/dashboard/charts/map.scss
Note that the positioning of the tooltip was also changed in this commit. Previously, the tooltip was `position: fixed`, which caused the tooltip to not scroll with the page. Switched it to absolute + added a new relative div to position it consistently across the choropleth and bubble maps.
fixes issue #353
> fix(visualization): Changed tooltip style for map

- src/components/pages/data/state-data.js
- src/components/pages/data/state-list.js
- src/scss/components/pages/data/state-data.scss
Fixes:
- The jump to top links were pointing to a non-existant anchor
- The crazy margin/padding trick to keep states visible with a fixed header was covering up the back to top link.
> State jump selector fix

- src/pages/dashboard/_SmallMultiplesContainer.js
- src/pages/dashboard/index.js
Uses the pattern established in #432 to query the data from the GraphQL API for the small multiples charts, instead of fetching data client side.
> Use GraphQL query for small multiples charts

- src/pages/dashboard/charts/_Map.js
Uses new custom color schemes for total test results and death maps.
Fixes COVIDTracking/website#349
> fix(choropleth): update color schemes

- src/scss/colors.scss
- src/scss/components/common/detail-text.scss
- src/scss/components/footer.scss
- src/scss/components/header.scss
- src/scss/components/hero.scss
- src/scss/components/pages/homepage/press-logos.scss
- src/scss/pages/data.scss
- src/scss/pages/homepage.scss
- src/stories/2-components/03-Colors.stories.js
This PR now includes [our updated (and _lovely_) color set](https://github.com/COVID19Tracking/website/issues/440#issue-596634505)! Specifically:
- In https://github.com/COVID19Tracking/website/compare/beep/440-colors?expand=1#diff-29f0bd10a1e22baf2f9585a9ae897e4fR3-R45 I’m proposing we adopt a `$color-[name]-[number]` naming convention, where the `[name]`s are borrowed from the actual color names in the palette. (So `$color-plum-3` instead of `$color-main-mid`, and `$color-slate-4` instead of `$color-grey-4`.)
- The exported color variables in https://github.com/COVID19Tracking/website/compare/beep/440-colors?expand=1#diff-29f0bd10a1e22baf2f9585a9ae897e4fR70-R100 follow a similar convention, but camelCase’d!
- References to the old color names have been updated, as have the references in …
> Updated color set, closes #440

- build/datasources/stateNames.js
- src/__tests__/API-CHECKING.md
- src/__tests__/build-test.js
Fixes #381 
This is a first stab at adding some testing around [API quality as referenced here](https://github.com/COVID19Tracking/website/issues/266#issuecomment-607249211). These first four tests add some basic data quality checks ensuring:
1.) Length of items in daily (us & states) array.
2.) Latest daily state data has at least 50 items.
3.) Latest daily states is subset of states (`./build/datasources/stateNames.js`)
While these are by no means comprehensive, it is a step forward. There are a couple of caveats:
1.) Since pulling the data from the spreadsheet during build time requires Google API keys, only privileged users with credentials will have the ability to reliably run these tests. Others, will have to manually pull from the site to the `./public/api` directory. I have …
> test(api): Add jest tests for API quality

- src/components/common/format.js
- src/components/common/summary-table.js
- src/components/pages/state/state-history.js
- src/pages/data/us-daily.js
- src/stories/2-components/02-Typography.stories.js
- src/utilities/format-date.js
- src/utilities/format-thousands.js
Fixes #458 
This PR:
- Moves the `formatDate` and `thousands` utilities to regular React components
- Makes numbers default to 'N/A' if not available so you don't have to have ternary operators all over the place
- Uses a more readable default date format
> feat: Centralize formatting functions into components, also, date formatting

- src/pages/dashboard/charts/_Map.js
As per https://github.com/COVID19Tracking/website/pull/450#issuecomment-611578337
Changed state border color to white on grey/deaths map for better contrast.
> Make state borders white on grey deaths map

- src/components/common/detail-text.module.scss
- src/components/layout/footer.module.scss
- src/components/layout/header.module.scss
- src/components/layout/hero.module.scss
- src/components/pages/data/state-data.module.scss
- src/components/pages/data/state-nav.module.scss
- src/components/pages/homepage/visualizations.module.scss
- src/pages/data/index.module.scss
- src/pages/index.module.scss
- src/scss/colors.scss
- src/stories/2-components/03-Colors.stories.js
As suggested by @jasonsantamaria, this PR proposes we adopt a `font-weight`-like naming scheme for our color variables. Specifically:
- Current color variables increment by steps of 100. (`$color-plum-100`, $color-plum-200`, and so on)
- Darker shades of each color—think “heavier weights”—are placed toward the upper range of each variable set. (`$color-honey-200` is lighter than `$color-honey-300`; `$color-honey-800` is darker than both)
Feedback/discussion welcome!
> Tweaking the color naming scheme (closes #460, closes #465)

- src/pages/dashboard/charts/_AreaChart.js
- src/pages/dashboard/charts/_BarChart.js
- src/pages/dashboard/charts/area-chart.scss
- src/pages/dashboard/dashboard.scss
- src/stories/2-components/15-Charts.stories.js
I didn't make much of any modifications to the components themselves.
The AreaChart & the BarChart now show up in storybook.  I also added PropTypes for both to make it clear what props are required and what types they should be.
We could probably do with some further cleanup to make these more friendly for use elsewhere.
The AreaChart specifically doesn't respect the height & width passed, it just seems to use them for proportions & relies on the container element to size it. (i'll add a issue on this one).
The map I'll have to think about a bit more (assuming anyone wants to use it elsewhere). It is a bit more entangled with it's container component at the moment.
> feat(dashboard): add charts to storybook

- src/components/pages/state/state-history.js
- src/pages/data/us-daily.js
- src/templates/state.js
This PR adds a tests per day ("New Tests") column to the US and state historical tables:
See #471
> Add tests per day to historical tables (closes #471)

- src/pages/dashboard/_MapContainer.js
- src/pages/dashboard/_StateCumulativeTestsContainer.js
- src/pages/dashboard/_utils.js
- src/pages/dashboard/dashboard.scss
- src/pages/dashboard/map-container.scss
This adds a toggle that allows user to switch the state cumulative tests charts between total number of tests and per capita testing amount.
- Existing state with population does not include the territories; added them as a [local hash in _StateCumulativeTestsContainer](https://github.com/vijaysharwar/website/blob/7e48dcd4db7e8249015bb3af02b809202b989212/src/pages/dashboard/_StateCumulativeTestsContainer.js#L72-L77)
- The data and state calling code (`MP`) are actually for "Northern Mariana Islands", not "Marshall Islands". [Renamed here](https://github.com/vijaysharwar/website/blob/7e48dcd4db7e8249015bb3af02b809202b989212/src/pages/dashboard/_utils.js#L40) as per conversation in https://github.com/COVID19Tracking/website/issues/479#issuecomment-612198044
- Changed `#map-style-button` to …
> Add toggle to switch between states' total tests versus per capita

- src/pages/dashboard/_MapContainer.js
- src/pages/dashboard/_StateCumulativeTestsContainer.js
- src/pages/dashboard/dashboard.scss
- src/pages/dashboard/map-container.scss
Updating the small area charts toggle and legend to make better use of available space on larger screens. See conversation in https://github.com/COVID19Tracking/website/pull/494#issuecomment-612313777.
- Uses updated toggle styles from https://github.com/COVID19Tracking/website/pull/500
- Moves `.map-toggle` to `.dashboard-toggle` and into `dashboard.scss`, since this
component is shared between the map and small area charts
cc @goleary @AaronMullan @julialedur
> Move chart legend to right of toggle on large screens

- src/pages/dashboard/_utils.js
- src/pages/dashboard/charts/_Map.js
- src/pages/dashboard/charts/map.scss
Fixes #477 
One question before merging this: I noticed the per capita numbers in the tooltip table had lots of digits after the decimal point... I updated the formatNumber util to render them as integers. Let me know if this is not what is desired.
> Fix tooltip tables styling

- src/templates/state.js
Fixes #507 
Reorders screenshots by `dateChecked` in ascending instead of descending order
> fix: Screenshot order

- src/pages/dashboard/charts/_Map.js
[355](https://github.com/COVID19Tracking/website/issues/355)
Resized the map
Before:
After:
> fix: resized map

- src/pages/dashboard/index.js
Fixes the spacing between contributor's names
----
Proposed:
Current:
> fix: dashboard contributor spacing

- src/components/pages/data/state-nav-no-script.js
I think I left this out in #523
> fix(state-nav-no-script): remove unused Link import

- src/components/common/container.js
- src/components/common/container.module.scss
- src/components/layout/header.module.scss
- src/components/layout/index.js
- src/stories/2-components/01-Layout.stories.js
- src/templates/content.js
This addresses #452, updating to use the narrow container for content pages on the site. I also felt like it needed some additional space between the header and start of the content on larger screens, but I defer to @beep and the design team.
Feedback welcome, especially since this is my first time poking my head into React.
> chore: Use narrow layout container for content pages

- src/pages/dashboard/_CDCComparisonContainer.js
- src/pages/dashboard/_UsCumulativeDeathsContainer.js
- src/pages/dashboard/charts/_BarChart.js
[503](https://github.com/COVID19Tracking/website/issues/503)
- Made the CDC bar charts smaller
- Made the bar chart text smaller 
- Added an `align` property to the bar chart
Before:
After:
After, for the Total cumulative deaths chart
> Update barchart size 503

- src/components/common/container.js
- src/components/common/container.module.scss
- src/components/layout/index.js
- src/pages/about-project/in-the-press.js
- src/pages/blog.js
- src/templates/blog-post.js
- src/templates/content.js
This PR resolves the design fixes for text-based pages, per [Ethan's designs](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh) in #452 
Here are some screenshots of this design:
@beep I would _love_ for you to review this :+1: 
Edit: since the scss changes are at the container level, they hit other pages as well:
I would suggest making a scss class for text-heavy pages and applying these styles there. @kevee what do you think?
> fix: text-heavy page design

- src/pages/dashboard/index.js
I think this looks better on the page.
> fix(dashboard): Makes the div containing the two death charts space better

- src/components/common/container.module.scss
current:
proposed :sparkles: :
(this mirrors the 1.5rem spacing on mobile for other pages)
> fix(text-heavy): add L/R margins on smaller viewports

- src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
> fix(charts): Add legend to "Positive tests and total tests in the US" chart

- src/pages/dashboard/charts/map.scss
Fixes #581
This does not affect positioning on small screen sizes, which currently looks like this:
> fix(dashboard): align map legend with toggle

- src/pages/dashboard/charts/_Map.js
- src/pages/dashboard/charts/map.scss
before:
after:
(change in position is a function of different window sizes while taking screenshots)
> fix(dashboard): update bubble legend style closes #593

- src/pages/dashboard/dashboard.scss
Fixes a minor display issue in small multiple charts caused by padding set on the individual charts. Now the left edges of the charts aligns properly with the heading/toggle. Also increases the gutters slightly at smallest breakpoint.
> fix(charts): adjust small multiples container for left and right alignment

- src/components/charts/area-chart.js
- src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
Fixes COVID19Tracking/website#567.
> fix(charts): remove M from y tick labels on pos tests chart (except last one)

- .typo-ci.yml
Added a config file for TypoCI. Mostly to teach it the word "covid"
> chore: Add config file for TypoCI

- build/datasources/sheets.js
Updated the sheet ID for press links. Closes #646
> chore: Change sheet ID for API per #646

- src/components/charts/bar-chart.js
- src/components/charts/horizontal-bar-chart.js
Looks like some merge conflict resolution snuck older markup back. In this PR:
- Removed width/height attributes in `BarChart` svg
- Removed unnecessary wrapper divs around `BarChart` and `HorizontalBarChart`
Fixes #644. Regression issues will be fully resolved with the additional merge of https://github.com/COVID19Tracking/website/pull/641.
> fix(charts): fix regression issues with charts layout and responsiveness

- src/pages/about-data/visualization-guide/index.js
Added subnavigation to the visualization page.
Fixes #672 
Anytime
> chore: Add visualization sub nav to page

- src/components/common/list-arrow.js
- src/components/layout/header.module.scss
- src/scss/global.scss
Fixes for https://github.com/COVID19Tracking/website/pull/638
* Fix reverted header menu/title on small screens  
* Add box-sizing declaration to HTML  
* Fix missing `key` attr in `list-arrow.js`
https://github.com/COVID19Tracking/website/pull/638
Still an issue with `<col>` being a direct child of `<table>` (see orig PR)
> fix(header): reverse mobile header title/menu

- src/scss/global.scss
Removing Typography.js seems to have eliminated global border-box sizing, which negatively affects several layouts in the Visualization Guide.
Setting box-sizing to border-box changes how the browser calculates width of elements, including their paddings in the final width calculation.
So if you have an element with width of 100px, and 20px left/right padding, the browser will render it at 100px with 60px of content area. Without border-box, that same container would be rendered to 140px total.
See comment in https://github.com/COVID19Tracking/website/pull/638#issuecomment-617871028.
> fix(typography): restore box-sizing globally

- src/utilities/visualization.js
In the chart data, "Massachusetts" only has one T.
N/A
> fix(dashboard): "Massachusetts" typo (minor)

- src/components/utils/format.js
Fixed a flash-of-wrong-date format in the US pages. By putting dates into timezones on the server, the client pulls the dates back.
Fixes #710
> chore: Remove timezone from date format

- src/components/layout/header.module.scss
Makes nav on narrow viewports full width, so it doesn't get squished up to the right of the header.
Fixes #712
> chore: Fix responsive nav on desktop

- .github/PULL_REQUEST_TEMPLATE.md
- netlify.toml
- package.json
This ensures that the full API build only occurs on `master` or specific deploy branches within Netlify. This should:
- Prevent bumping against API call limits
- Cause developer previews to build *way faster*
This only affects Netlify, CircleCI would continue to run API tests under #705 
If a build in Netlfy is a deploy preview, it will run `npm run build-preview`, which **downloads** the API file tarball from the website, and does not run `npm run build:fetch`.
> chore: Make API build a production-only command

- src/components/pages/blog/byline.module.scss
Testing!
Make sure that running `npm run test` works locally before opening a PR.
tests passing locally
fixes - blog headshots are stretched on Safari #759
blog headshots are stretched on Safari #759
> fix(visual): blog headshots are stretched on Safari #759

- src/context/search-context.js
- src/utilities/algolia.js
This:
- Adds contentful_id to blog and page indexes
- Flags the field as distinct using `attributeForDistinct`, but doesn't filter them out in the index
- Uses `distinct` to only return one value per record
Fixes #761
> feat: Add distinct field to search

- src/__tests__/components/layout/__snapshots__/header.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/layout/header.js
- src/pages/index.js
So we don't hit a redirect and force a page refresh, change the "Get Involved" link component in the header to /about-project/help
> fix:Change path for get involved #769

- src/components/pages/homepage/header-hero.js
- src/components/pages/homepage/header-hero.module.scss
Adjust CSS for hero chart so that it is responsive per #778
> fix(design): Homepage hero chart is more responsive

- build/__tests__/post-build/v1/states/all-states.js
- build/datasources/screenshots.js
- build/datasources/states.js
- build/datasources/statesDaily.js
- build/datasources/statesInfo.js
- netlify.toml
- Removes upper-case state names in API routes, since Netlify automatically matches paths to lower-case.
- Removes unused FIPS-based file paths.
> chore: Use only lower-case paths in API

- src/components/pages/homepage/header-hero.js
Add "tests" after our count in the hero.
[Slack thread](https://covid-tracking.slack.com/archives/C0133BX4H7E/p1588885928027800)
> fix(hero): add 'tests' after our count

- src/components/pages/homepage/header-hero.js
- src/components/pages/homepage/header-hero.module.scss
- src/scss/global.scss
Quick fixes for the homepage hero: 
* Add some spacing between title and paragraph  
* Prevent `so we are.` of being wrapped.
https://github.com/COVID19Tracking/website/issues/832
> fix(hero): nowrap last part of title, add some spacing

- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/__tests__/components/layout/index.js
- src/components/layout/index.js
- src/templates/blog-post.js
also adds a displayTitle param to Layout
- this separates the SEO title (html <title>) from the page title *displayed* in the header
Removes the highlighted blog title on individual blog pages
> fix(blog): rm duplicate blog title

- src/components/layout/header/header.module.scss
In order to address the potential for wrapped sub nav items, we keep the 1em left margin on the first item, as well as the 1em right margin on the last item, and compensate by adding a -1em left and right margin on the containing element. 
https://github.com/COVID19Tracking/website/issues/856
**Before:** 
**After:**
> fix: sub-nav

- src/components/layout/header/header.module.scss
Fixes issue https://github.com/COVID19Tracking/website/issues/870, which was introduced recently by pull request https://github.com/COVID19Tracking/website/pull/863
Since we have added a negative margin on the containing element, we need to account for this with a margin on the items inside. I missed the media query in the initial work. 
I also changed the em unit of the negative margin to rem since we seem to use rem throughout. 
Fixes https://github.com/COVID19Tracking/website/issues/870
Related to https://github.com/COVID19Tracking/website/issues/856
> fix: subnav margin

- src/components/pages/race/charts/county-chart.js
- src/components/pages/race/charts/index.js
- src/components/pages/race/citation.js
- src/components/pages/race/header-hero.js
- src/pages/race/index.js
[ARPC Copy Edits](https://github.com/COVID19Tracking/website/projects/10#card-38478741)
- Header section, support graf
- [Change end of last sentence from “in the US anywhere.” to “in the United States.” ](a377ca7f31cf0532280bf41bfa3777603b8be0e2)
- County intro copy, first graf
- [Change “wildly” to “vastly” ](https://github.com/COVID19Tracking/website/pull/877/commits/ae586da4dbfd3e74e7b8c494084a91418c33286b)
- County intro copy, second graf
- [Italicize New York Times](4b1f94813d0ced16d6844eec0fc7b48d3474ebda) 
- [Add words in “we do have: infection” to read “we do have: the latest infection” ](643ce0d0bcfb46d303652ec7aec00a26d88b8224)
- [Change rest of sentence from “paired with” onward to “paired with the largest racial or ethnic group in that county, based on the Census Bureau's …
> fix(text): ARPC copy edits

- src/components/pages/race/charts/county-chart.js
- src/components/pages/race/charts/index.js
- src/components/pages/race/citation.js
- src/components/pages/race/header-hero.js
- src/pages/race/index.js
Corrected spelling (_transfrorm_ to _transform_) and realigned labels to chart bars once the transform worked
> fix(chart): Corrected spelling

- .gitignore
- gatsby-config.js
- package.json
- src/components/pages/race/dashboard/states.js
- src/pages/race/dashboard.js
This adds the real API endpoint to the race project dashboard. Notes:
- It uses data from `./_api` which is a cloned repo
- You must run `npm run setup` or to not wipe your envvars, `npm run setup:api-repo` to clone the data
- Some fields (duplicates) have changed, I updated the big GraphQL query, but didn't do QA on everything
> chore: Change data source to API repo

- src/components/pages/race/multiplier-highlight.js
- src/pages/race/index.js
[Added cases](https://github.com/COVID19Tracking/website/projects/10#card-38544863) for the deaths / percent of the population ratio, so that we get standard language instead of a specific number
* For deaths / population < 1.36, the sentence does not show up at all
* currently, the cases account for up to deaths / population of 3.35, for anything higher I included 'much higher'
> fix(logic): added language for death rate ratio cases

- src/__tests__/components/pages/homepage/__snapshots__/press.js.snap
- src/components/layout/header/navigation.js
- src/components/pages/homepage/press.js
- src/components/utils/internal-link.js
- Fixes hot-reload issue created by non-class component in MenuList
- Fixed a few non-base-relative Link components
Fixes #925
> fix: Hot reload ownerDocument error, Gatsby links

- .github/PULL_REQUEST_TEMPLATE.md
This shortens the PR template to include just one preamble comment about docs and testing. It removes the stubbed-out go-live and post-merge steps.
> chore: Shorten PR template

- src/components/common/state-nav.js
This is a new fix for #551. I have successfully tested on multiple Android and iOS devices using Browserstack, as well as multiple desktop browsers.  
Thanks to @pspeter3 for the recommended approach!
> fix: Improve handling of blurring jump-to-state input

- .github/workflows/api-test.yml
- jest.config.js
- package.json
- src/__tests__/api/index.js
This runs a github action that ensures all CORS headers and proxies for old API URLs are set. It leaves a comment on the PR with the output of a JEST test.
> feat: Add API post-build testing

- functions/api-build/api-build-test.js
Add Netlify function to do a staging webhook for the API
> chore: Add staging endpoint

- src/stories/2-components/01-Layout.stories.js
- src/stories/2-components/02-Typography.stories.js
- src/stories/2-components/type-size.module.scss
- Adds actual type size samples to storybook
- Put a preamble to the spacer page to let users know how to use the mixin.
> chore(docs): Add type sizes to storybook

- src/components/pages/race/charts/county-chart.module.scss
Removed absolute width breaking the charts on the CRDT homepage.
> fix: Absolute bar width on charts

- plugins/gatsby-source-covid-tracking-api/gatsby-node.js
- Changes the error message that is displayed if a user tries to run gatsby without the API files downloaded
- Fixes #1042
> chore(docs): Change fail message in plugin

- src/components/common/state-nav.module.scss
> fix(crdt): nav-bar overlaps states popover

- src/components/common/press-list.module.scss
- src/components/common/volunteers-list.module.scss
- src/components/pages/state/state-links.module.scss
- src/scss/global.scss
- Removes global ul/ol stlyes
- Makes the one component that depended on those styles declare the styles explicitly
> chore: Cleanup list elements

- src/pages/data/download.js
Adds a return link for the new download page introduced in #1033
> chore: Add return link to data from download page

- .github/workflows/sync-contentful-preview.yml
- src/stories/1-docs/6-Contentful.stories.mdx
- Added docs about the preview environment
- Added docs about social cards & clarified fields in blog posts.
- Made a Github action to auto-open a PR to `contentful-preview`. Fixes #1055
> Contentful docs and auto-syncing contentful-preview

- src/__tests__/components/pages/data/__snapshots__/state-data.js.snap
- src/__tests__/components/pages/data/__snapshots__/state-list.js.snap
- src/__tests__/components/pages/state/__snapshots__/state-links.js.snap
- src/components/common/state-nav.js
- src/components/pages/data/state-data.js
- src/components/pages/data/state-list.js
- src/components/pages/state/state-links.js
- src/templates/state.js
Tracks anonymous [goals with fathom](https://usefathom.com/support/goals) for:
- Click on state twitter or info pages from data page
- Click on state twitter or info pages from state pages
- Use of state nav on data page
> Track state data page use with Fathom goals

- src/pages/contact/index.js
> Add autoreply fields to contact form

- src/__tests__/components/pages/data/__snapshots__/state-nav.js.snap
- src/components/common/state-nav.js
> fix(state-combo): Workaround to prevent chrome from autofilling

- src/components/layout/header/index.js
- src/pages/about-data/visualization-guide/index.js
- src/pages/about-project/index.js
- src/pages/api.js
- src/pages/data/index.js
- src/pages/data/us-daily.js
- src/templates/content.js
- Removes references to pages in Navigation Groups, and only uses Navigation Links
- Fixes #1094
> chore: Remove page-associated links from navigation

- src/pages/contact/index.js
In Front it turns out that when emails come from support@covidtracking.com they automatically get copied to the General Support inbox no matter what rules I set, so I've set up a Google Group with the address contact@covidtracking.com with me as the owner and only member to serve as the From address for autoreplies to Contact form submissions
> Changes contact form autoreply address

- src/__tests__/components/pages/data/state-nav.js
- src/components/common/state-nav.js
My first instinct for searching a state was to type the two character state code which showed no results, since it seems we only search on strict state / territory name.
This updates to also strictly search on the `state` property which is the expected state code (and `DC` for District of Colombia and `PR` for Puerto Rico).
> feat: include state codes in state search

- package-lock.json
- package.json
- src/__tests__/components/layout/__snapshots__/footer.js.snap
- src/__tests__/components/layout/__snapshots__/header.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/layout/footer.js
- src/components/layout/footer.module.scss
- src/components/layout/header/navigation.js
- src/components/layout/header/search/index.js
- src/components/layout/header/search/search-autocomplete.js
- src/components/layout/header/search/search-autocomplete.module.scss
- src/scss/global.scss
- src/scss/helpers.module.scss
Fixes #1078 
- Adds escape key handler to autocomplete that auto-blurs the search and closes it
- Removes tabindex on the autocomplete input so it's not tabbable when minimized
- Removes overridden `MenuButton` component so we have better native keyboard handling from Reach-UI
- Adds new `a11y-only()` mixin
- Used mixin on label for search box when hidden, and the "Back to the top" part of the footer when hidden
- Removed unused `role` from menu dropdowns.
> chore: Fix keyboard trap in search box

- src/components/layout/header/search/search-autocomplete.module.scss
The display `none` on the search label is ok from an a11y perspective because it's displayed on focus.
> chore: Fix hidden label

- src/components/layout/header/header.module.scss
The text inside the "Get Involved" button is not vertically centered at smaller viewports.
Currently, it looks like this:
This PR centers the text:
> chore(nav): center get involved button on small viewports

- src/templates/blog-category.js
Fixes issue #1126 by adding a return link to the blog in the blog category layout.
Screenshot:
> fix(design): Add link back to blog on blog category pages

- gatsby-node.js
> chore: check for content type before checking if content is an image

- src/__tests__/components/pages/homepage/__snapshots__/press.js.snap
- src/components/pages/homepage/blog-list.module.scss
- src/components/pages/homepage/press.js
- src/components/pages/homepage/press.module.scss
- src/pages/index.js
- Fixes #1134
- Switches order of press and blog sections on the homepage
> chore: Reorder press and blog sections

- src/components/common/summary-charts.js
> fix: update incomplete data warning text closes 1154

- src/__tests__/components/layout/__snapshots__/header.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/__tests__/components/layout/header.js
- src/components/layout/header/index.js
- src/components/layout/index.js
- src/templates/blog-post.js
- Makes the header title and subnavigation not in a centered container
- Adds a `centerTitle` prop for blog posts
> fix: Remove center from header unless on blog post

- src/components/pages/data/charts/chart-list.js
- src/pages/data/charts.js
- src/templates/chart.js
Adds the chart categories on the bottom of every chart page.
> chore: Add categories to the bottom of a chart

- src/components/common/summary-charts.js
> fix: Summary chart padding

- src/data/navigation/header.yml
- src/pages/about/newsletter.js
- src/pages/contact/index.js
- src/pages/contact/volunteer.js
- src/pages/data/index.js
- Fixes some pages missing subnav
- Adds contact pages to the about-us navigation
> chore: Change page URLs and add missing navigation links

- src/components/common/form.js
- src/components/pages/contact/volunteer-form.js
WIP as we figure out the deal with Netlify.
Fixes #1220
> fix: Input names on radio buttons

- src/components/pages/contact/volunteer-form.js
Fixes missing form name in volunteer form. Fixes #1220
> chore: Fix Volunteer form name

- gatsby-config.js
- src/components/pages/blog/blog-content.js
- src/components/pages/blog/blog-footnotes.js
- src/components/pages/blog/blog-footnotes.module.scss
- src/templates/blog-post.js
- Adds support for embedded tableau content blocks
- Adds stubbed-out support for footnotes
> feat: Tableu embeds and footnotes

- src/components/pages/blog/blog-content.js
- src/components/pages/blog/image-content-block.js
- src/components/pages/blog/image-content-block.module.scss
Adds support for the "Keep regular image size" checkbox in Contentful.
> chore: Handle sizes that keep their native sizes

- src/components/pages/race/dashboard/anhpi-notes.js
> fix(anhpi-notes): typo in nhpiDeathCaution

- src/components/pages/data/api/explorer.js
- Adds markdown support to descriptions in API
- Part of https://github.com/COVID19Tracking/covid-public-api-build/pull/78
> chore: Add markdown support to API descriptions

- src/components/pages/blog/author-footer.js
- src/components/pages/blog/blog-extras.js
Fixing #1272 
Returning `null` for the AuthorFooter component when there are no author bios does not remove the hr.
Conditional rendering in BlogPostExtras component would remove hr when there are no biographies.
> fix(design): null when author bio missing

- src/components/layout/header/header.module.scss
Removes a white space above the header in Safari.
> fix: Safari white space above header

- src/components/charts/bar-chart.js
- src/components/common/summary-charts.js
> feat: Add /1M label to per cap summary charts y-axis

- src/components/common/summary-charts.js
They have 10 days of data as of today and we want to show that despite the 30% out of the last 90 day requirement to display a graph.
> chore: exempt Hawaii from 30 day data requirment on summary charts

- src/__tests__/components/pages/race/dashboard/__snapshots__/breakdown-tables.js.snap
- src/__tests__/components/pages/race/dashboard/__snapshots__/percent.js.snap
- src/components/pages/race/dashboard/percent.js
- Refactors CRDT dashboard percentage display to only display `0%` if there is actually zero percent, instead of zero after rounding.
- Fixes #1305
> chore(crdt-dashboard): Fix less than zero percent display

- src/components/common/summary-charts.js
- src/components/pages/data/api/explorer.js
- src/pages/data/api.js
- Adds a note about the change of the API domain to `api.covidtracking.com`
> chore: Change API domain name

- src/pages/contact/index.js
> Fixes #1321 - removes media inquiries from contact form dropdown

- src/components/charts/bar-chart.js
fix for issue #1293
-if maximum y-value is less than 4, the same number of corresponding y-ticks will be displayed
-changed default value of yTIcks to null to allow a specified yTicks argument to override code logic
> fix(charts): Fixed yTicks issue at low y-values

- src/components/common/summary-charts.js
This shouldn't change anything since FL has now been reporting hosp data for 30 days (:tada:), but it'll clean up the code a bit.
Fixes #1330
> fix(summary-charts): stop exempting Florida from data reqs

- src/components/pages/race/dashboard/percent.js
Fixes #1309
Handles non-null empty strings as null values in the CRDT dashboard
> chore: Handle empty string values

- static/_redirects
Changes all API traffic to redirect to `api.covidtracking.com`. Should merge no later than August 17
> [⚠️Merge Aug 17] chore: Update redirects file

- src/components/pages/blog/byline.module.scss
> fix(blog): remove on hover underline for blog authors without links

- src/components/common/summary-table.js
Change RI to use total test encounters
> chore: Use encounters for RI

- src/__tests__/components/common/__snapshots__/table-of-contents.js.snap
- src/__tests__/components/common/table-of-contents.js
- src/components/common/table-of-contents.js
- src/components/common/table-of-contents.module.scss
- src/templates/content.js
- Uses an `enableToc` field in Contentful to turn on a table of contents
- Creates a simple TOC on the top of the page with links to `h2` headings
- Fixes #1337
> feat: Add table of contents

- src/__tests__/components/pages/race/__snapshots__/cta-links.js.snap
- src/components/common/landing-page/call-to-action.js
- src/components/pages/race/cta-links.js
Adds fathom Goal to CRDT download link.
> chore: Add fathom to track CRDT downloads

- src/components/pages/data/summary-charts.js
Removes duplicate snippet from below charts.
> chore: Remove disclaimer snippet

- src/components/common/last-updated.module.scss
- src/components/pages/data/summary-charts.js
- src/components/pages/data/summary-charts.module.scss
- src/components/pages/state/download-data.js
- src/components/pages/state/preamble.js
- src/components/pages/state/preamble.module.scss
- Fix header order of state preamble
- Fix header order of summary charts
- Darken the last update component to meet color contrast requirements
> chore(a11y): Fix color contrast, header depth

- src/pages/data/national/index.js
- src/utilities/csv.js
- Adds a US national daily CSV file
- Adds links to that file, the API, and spreadsheet to the national history page
- Fixes #1368
> chore: Add US historical CSV data to National page

- src/components/pages/data/ltc/download-links.js
- src/pages/data/longtermcare.js
- Adds new snippet
- Adds new chart
- Changes URL for downloading dataset
> chore: Add LTC death charts

- src/utilities/csv.js
Adds `deathIncrease` to national CSV download.
> chore: Add deathIncrease column

- src/components/pages/data/summary-charts.js
Removes comparison of state tests to US tests by 1M because they are mixing units.
> chore: Remove US daily average from test chart

- src/pages/data/national/cases.js
- src/pages/data/national/hospitalization.js
- src/pages/data/national/index.js
- src/pages/data/national/outcomes.js
- src/pages/data/national/tests.js
- Adds definitions to national history subpages
- Fixes formatting of US totals page
> feat: Add definitions to national sub-pages

- src/components/common/table-responsive.js
- src/pages/data/download.js
- src/pages/data/national/cases.js
- src/pages/data/national/hospitalization.js
- src/pages/data/national/outcomes.js
- src/pages/data/national/tests.js
- src/templates/state/cases.js
- src/templates/state/hospitalization.js
- src/templates/state/outcomes.js
- src/templates/state/tests-antibody.js
- src/templates/state/tests-viral.js
- Refactors responsive table to remove duplicate field formatter
> chore: Refactor responsive table

- src/utilities/csv.js
Fixes https://github.com/COVID19Tracking/covid-public-api-build/issues/98
- Adds "pending" to the all-states-daily CSV
> chore: Add pending to all-states-daily export

- src/pages/data/longtermcare.js
Update chart height in LTC landing page.
> chore: Set chart height

- src/pages/data/longtermcare.js
Changes order of LTC landing page.
> chore: Move chart note to below deaths chart

- src/__tests__/components/common/__snapshots__/last-updated.js.snap
- src/components/common/last-updated.js
- src/components/common/last-updated.module.scss
- src/pages/data/index.js
- Fixes #1381 
- Reformats latest date component
> chore: Reformat timestamp

- src/components/pages/blog/blog-categories-list.js
- src/components/pages/blog/blog-categories-list.module.scss
Resolves #1404
This PR adds a wrapper div to the blog categories list so it has the height of the content instead of the column (see screenshot).
Since this is my first PR, I wanted to introduce myself real quick as well. I'm a full-time freelancer based in Indiana. I specialize in WordPress and Vue.js but I've done a little bit of React work in the past. I'll keep looking through the issues list but I'd love to contribute more to this project.
Let me know if this PR looks alright and feel free to reach out! I'll keep familiarizing myself with the project.
> fix(design): reduce height of blog categories to the content

- src/components/layout/header/return-links.js
Resolves #1409
I looked into this and the string "All Posts" is coming from `blog-category.js` when the return link is passed into the `<Layout />` component.
To fix, I updated `return-links.js` to access the elements of the `topNavigation` array by clone instead of by reference.
I'm still learning how Gatsby's SSR works under the hood but I'm speculating this only occurred in the SSR because `BlogCategoryTemplate` gets imported as its rendering all the pages and not when the JS on the individual pages loads up.
> fix(nav): SSR is rendering "All Posts" in navigation instead of "Blog"

- src/pages/about-data/data-definitions.js
- Hides API-only definitions from the definitions page.
> chore: Hide API-only definitions in definitions page

- src/__tests__/components/layout/__snapshots__/footer.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/layout/footer.js
Changes the footer license to CC BY 4.0
> chore: Change license in footer

- src/components/pages/data/ltc/download-links.js
> chore: Fix link to cumulative dataset

- src/components/pages/state/preamble.js
Since we switch the download link component out for mobile, the slug in the URL was broken. This fixes that.
> fix: Missing slug in CSV download link in mobile

- src/components/pages/data/ltc/download-links.js
> chore: Change link to LTC notes CSV

- src/pages/data/longtermcare.js
- Adds snippet collection support to the LTC landing page
> feat: Use snippet collections to define long-content

- src/components/pages/race/charts/county-overview-charts.js
- Fixes bug where we had not fully listed all possible number-to-word conversions in the CRDT homepage
> chore: Complete conversion of number to words in CRDT

- .circleci/config.yml
- Removes build dependency of the storybook workflow
> chore(ci): Make storybook a parallel workflow

- package.json
- src/templates/state/tests-viral.js
- Uses new `totalTestResultsField` as source for history title
- Removes state-specific formatting for test history page.
> feat: Switch test history table using `totalTestResultsField`

- src/components/charts/tableau.module.scss
Fixes Charts truncated on iPad #1428
Per conversation with Peter Walker, this just changes the breakpoint at which the mobile design loads instead of the desktop one.
> fix(design): Changed breakpoint so tablets display mobile chart design

- package.json
> fix: Add data repo to production build

- src/components/pages/blog-features/scrollytelling/index.js
- src/utilities/scrollama.js
Hack scrollama to just override all instances of `window` if undefined
> chore: Hack scrollrama

- src/components/utils/format.js
previously, a zero would result in 'N/A' since zero was evaluated
as false. this instead adds an explicit null check, which returns
zeros as zero, not 'N/A'.
> fix(format-number): handle zeros properly

- gatsby-config.js
- src/components/layout/header/navigation.module.scss
- Fixes #1463 by setting seven days ago against the most recent date in US daily
- Fixes #1457 by removing an unused `[data-selected]` CSS selector that is always set on SSR
> chore: Fix 7 days ago date, hover CSS

- src/__tests__/components/pages/homepage/__snapshots__/blog-list.js.snap
- src/components/pages/homepage/blog-list.js
> fix: Missing date on homepage blog posts

- plugins/gatsby-source-covid-tracking-counties/gatsby-node.js
- A console log entry was missed in linting
> chore: Remove console log from counties plugin

- src/__tests__/components/pages/data/__snapshots__/state-nav.js.snap
- src/components/pages/data/state-nav.js
- Adds `abbr` tags to improve accessibility of the state navs
> fix(a11y): Label state nav with abbr

- plugins/gatsby-transformer-covid-census/gatsby-node.js
- Fixes 7-day average population calculation for US numbers
> fix: US Population missing from BQ results

- src/utilities/csv.js
Sorts the state history CSVs by date and state name
> fix: Sort all states CSV by date, state name

- .github/PULL_REQUEST_TEMPLATE.md
- Removes hacktoberfest warning from PR templates
> chore: Remove hacktoberfest warning from PR template

- src/pages/about-data/total-tests.js
- Adds `totalTestResultsField` to the total test results page table
> chore: Add total test results to total tests page

- src/__tests__/components/pages/data/__snapshots__/definitions.js.snap
- src/__tests__/components/pages/data/definitions.js
- src/components/pages/data/definitions.js
- src/pages/data/national/cases.js
- src/pages/data/national/hospitalization.js
- src/pages/data/national/index.js
- src/pages/data/national/outcomes.js
- src/pages/data/national/tests.js
- src/templates/state/cases.js
- src/templates/state/hospitalization.js
- src/templates/state/outcomes.js
- src/templates/state/tests-antibody.js
- src/templates/state/tests-viral.js
- Adds an `order` prop to the definitions component for state history pages
- Fixes #1502
> chore: Add order prop to definitions component

- src/components/pages/blog/content-blocks/image-content-block.js
Fixes #1500 
I added the native lazy loading attribute to blog images which do not use Gatsby Image. Native lazy loading is [supported by](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility) most desktop browsers, the exceptions being IE and Safari (Safari is working on implementing it). I found a polyfill [dependency](https://github.com/mfranzke/loading-attribute-polyfill) we could use to get it working in Safari. But since this is not a critical function, I'm not sure it justifies adding another dependency or the potential confusion of additional code.
> Add native lazy loading to blog img elements

- gatsby-config.js
- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/footnote-content-block.js
- src/components/pages/blog/footer/blog-footnotes.js
- src/templates/blog-post.js
- Uses a new "Content block: Footnote" inline block element to render footnotes.
- Fixes #1504 - Adds a link back to the inline footnote block
- Fixes #1499 - Formats the footnote link as a superscript link
> chore: Add footnote block support

- gatsby-node.js
Fixes missing redirects from contentful ID based redirects
> chore: Fix shortened contentful blog redirects

- src/__tests__/components/common/__snapshots__/table-responsive.js.snap
- src/components/common/table-responsive.js
- src/components/common/table-responsive.module.scss
Fixes an esoteric issue with CSS minified class names and labels in responsive tables
> chore: Force hide responsive table labels on desktop

- src/components/pages/state/download-data.js
Per our [deprecation announcement](https://apichanges.covidtracking.com/deprecation-of-the-public-spreadsheet-172468), this removes the public sheet from the website.
> chore: Remove link to public spreadsheet

- src/__tests__/components/layout/__snapshots__/header.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/layout/header/mobile-menu.js
- src/components/layout/header/tools.js
Renames the "Get involved" button to "Volunteer"
> chore: Change from "Get involved" to "Volunteer"

- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/related-posts-block.js
- src/components/pages/blog/content-blocks/related-posts-block.module.scss
- use subtitle instead of lede
- update styles: bullets and padding
- conditionally pass subtitle without breaking code for nulls
fixes #1534
> chore(related-posts): clean up design, code

- gatsby-node.js
- plugins/gatsby-source-covid-tracking-tweets/gatsby-node.js
- src/__tests__/components/common/__snapshots__/tweet.js.snap
- src/components/common/tweet.js
- src/components/pages/data/daily-tweet.js
- src/components/pages/state/state-tweets.js
- src/components/pages/state/state-tweets.module.scss
- src/templates/state/index.js
Draft PR to add tweets about a state to the footer of the state's data page.
> feat: Add tweets to footer of state page

- gatsby-node.js
Finds tweets for a state based on name, or capitalized abbreviation
> chore: Search tweets with state abbreviation

- src/pages/data/index.js
- src/pages/data/longtermcare.js
- src/pages/data/national/index.js
- src/templates/state/index.js
- src/utilities/csv.js
- Sorted fields in long queries
- Removed unused fields in state and data pages
> chore: GraphQL audit

- src/components/pages/blog/footer/related-posts.js
This handles a special case for blog categories such that related weekly update posts appear like:
...instead of:
> feat(blog): update language for related weekly update posts

- plugins/gatsby-source-covid-tracking-counties/gatsby-node.js
- src/utilities/csv.js
- Fixes issue with counties with padded FIPS code in NYT dataset
- Sort counties CSV file by state, then county name
> chore: Sort counties CSV by state, name

- README.md
- Adds more context for how long project takes to build when running `yarn develop`
- Updates command `yarn setup:api-data` to `yarn setup:api-repo` to match what's in `package.json`
> improvement(docs): Adds approximate project build time

- gatsby-node.js
- package.json
- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/related-posts-block.js
- src/components/pages/blog/footer/blog-footnotes.js
- src/components/pages/state/long-term-care/facilities.js
- src/pages/blog/test-positivity.js
- src/templates/blog-post.js
- src/templates/state/long-term-care.js
- src/utilities/algolia.js
- yarn.lock
To solve caching issues with Contentful rich text fields, this PR:
- Hard sets `gatsby-source-contentful` to `4.0.0-4.0.0-rc.0.20` - we'll have to update later and I'll make a note of that in Airtable
- Uses the new [references format](https://github.com/gatsbyjs/gatsby/pull/25249), which means no `en-US` field names, and no pre-fetching blog images 🎉 
- Updates all block and inline blocks to the new format
- Refactor the footnote area
> feat: Refactor contentful rich text to canary version

- gatsby-config.js
- package.json
- plugins/gatsby-source-covid-tracking-api/gatsby-node.js
- yarn.lock
- Removes unused JSON transformer
- Adds reporter for the COVID API source plugin
> feat: Add reporter feedback for API loader

- src/__tests__/components/pages/data/__snapshots__/cards.js.snap
- src/__tests__/components/pages/data/cards.js
- src/components/pages/data/cards/tests-antibody.js
- src/components/pages/data/summary.js
- src/pages/data/index.js
- src/templates/state/index.js
- [Airtable card](https://airtable.com/tbl78phKvQLbKQvV0/viwzuvy3fZrep0aoD/recslAdtoX6OSGJWq)
- Adds total antibody tests in people to antibody tests card
- Clarifies units for `totalTestsAntibody`
> feat: Add more fields to antibody tests card

- src/__tests__/components/pages/state/__snapshots__/state-notes.js.snap
- src/components/pages/data/cards/cases-card.js
- src/components/pages/data/state-data.js
- src/components/pages/data/summary-charts.js
- src/components/pages/data/summary-charts.module.scss
- src/components/pages/state/state-notes.js
- src/components/pages/state/state-notes.module.scss
- src/scss/global.scss
- src/templates/state/index.js
- Moves state notes to below the charts on the state page
- Makes state notes a maximum height of 15 rem and provides a toggle
- The notes should fail to expanded if JS is disabled
> chore: Shorten notes to an expandable block

- src/__tests__/components/pages/data/__snapshots__/summary-chart-description.js.snap
- src/__tests__/components/pages/data/summary-chart-description.js
- src/components/pages/data/summary-chart-description.js
- src/components/pages/data/summary-charts.js
- Generates an automatic description for state and national charts
> feat: Add automatic description to charts

- src/components/pages/blog/byline.js
Limit headershots to 3 in blog headers
> chore: limit headshots to 3 authors in blog headers

- src/__tests__/components/pages/data/__snapshots__/cards.js.snap
- src/components/pages/data/cards/cases-card.js
- src/components/pages/data/cards/hospitalization-card.js
- src/components/pages/data/cards/long-term-care.js
- src/components/pages/data/cards/outcomes-card.js
- src/components/pages/data/cards/tests-antibody.js
- src/components/pages/data/cards/tests-national.js
- src/components/pages/data/cards/tests-viral.js
- src/components/pages/data/summary.js
From user feedback, adds state names and data name to "more info" links in state cards so the link rotor doesn't keep repeating itself.
> feat(a11y): Better link text in cards

- src/components/pages/state/long-term-care/preamble.js
- src/templates/state/long-term-care.js
Removes the state grades from the LTC subpages
> chore: Remove state grade from LTC subpage

- src/utilities/algolia.js
We no longer are using the blog body field so we don't
need to worry about supporting that case.
Closes #1553.
> chore(algolia): remove unnecessary if statement

- src/components/pages/state/long-term-care/summary-table.js
- Uses both aggregate and outbreak facilities to determine which types to show in state summary tables
> chore: Use aggregate & outbreak to determine facilities

- src/components/pages/data/cards/long-term-care.js
- src/components/pages/state/long-term-care/overview.js
- src/components/pages/state/long-term-care/preamble.js
- src/pages/data/index.js
- src/templates/state/index.js
- src/templates/state/long-term-care.js
- Use state-level data for facility totals
- Rename facility totals
> fix: Long term care facility totals

- src/components/pages/data/cards/definitions-panel.js
- src/components/pages/data/states.js
This supports a format change in our Airtable annotations
> chore: Change to use single-value for field for annotations

- gatsby-node.js
- src/components/common/tweet.js
- only matches "CO" instead of "COVID" for Colorado
- also matches "CA," and "CA." as well as "CA"
- also applies to full state names i.e. California
- fixes #1621
>  fix(tweets): regex and highlighting

- src/pages/contact/data.js
Fixes #1591: stops autofilling state selector for contact page.
See [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) for more.
> fix(contact): disable form autofill

- src/components/pages/data/summary.module.scss
- src/components/pages/state/preamble.module.scss
> fix(data): content spacing for states

- gatsby-config.js
- src/components/common/toggle.module.scss
- src/components/pages/race/get-better-data/state-contact.module.scss
- Test and didn't see updated snapshots 
- Noticed the react components did have the child shown of the space, but, due to collisions, wasn't rendering 
-> investigation here showed me https://github.com/COVID19Tracking/website/issues/1608#issuecomment-731599590 (thanks @ivarvong )
- see source space between `:` and `Civil services`
before: 
after:
> fix(design): Remove style collision removing space

- src/pages/contact/data.js
fixes #1638
The name and id for contact-date appear to only have relevance for the webhook the form is submitting to. It does not appear to affect anything else in the website code, but I cannot say if it is being used in whatever is receiving the JSON. I hope this was useful!
> fix(contact): Edit id and name values for form on data contact page

- gatsby-config.js
- src/components/pages/data/charts/chart-list.js
- src/components/pages/data/charts/chart-list.module.scss
- src/components/pages/data/charts/map.js
- src/components/pages/data/charts/map.module.scss
- src/components/pages/data/charts/preamble.js
- src/components/pages/data/charts/preamble.module.scss
- src/components/pages/data/charts/sparklines.js
- src/components/pages/data/charts/sparklines.module.scss
- src/components/pages/data/charts/tweet.js
- src/pages/data/charts.js
- src/scss/helpers.module.scss
- Adds sparklines, map, and chart images to the chart landing page
> feat:Chart page redesign

- src/components/pages/data/charts/map.js
- src/components/pages/data/charts/map.module.scss
Fixes color contrast problems with the US map
> fix(a11y): Better color contrast

- src/__tests__/components/layout/__snapshots__/header.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/layout/header/mobile-menu.js
- src/components/layout/header/tools.js
Removes the volunteer button from the header
> chore: Remove volunteer form

- src/components/pages/race/infection-and-mortality-data/select.js
When selecting a new state in the dropdown in `/race/infection-and-mortality-data` it adds the URL with the new hash to history. Previously when navigating back after selecting two or more states, the hash would change but the state would not update. Now we listen for the hash change and update the state with backwards navigation.
> feat: Listen to URL hash change in race/infection-and-mortality-data to update state.

- src/components/pages/get-involved/form.js
- src/components/pages/get-involved/form.module.scss
fixes #1589
Added name fields back to the get involved page. I used the Col component to organize the input fields into one column since three fields are better organized as a single column rather than the original four in a 2x2 grid. Attached is a screenshot of the final look. It looks similar if implemented with the Row component or without a grid if that's a preferable frame for it to be in, so I can change it to those if need be.
> chore(get-involved): add name fields

- src/components/pages/data/charts/map.js
- src/components/pages/data/charts/map.module.scss
- src/components/pages/data/charts/preamble.js
- src/pages/data/charts.js
Change the US map on the charts page to be a seven-day average comparison
> chore: Change to seven-day average for map

- src/utilities/schema.js
Adds static schema definition for `ltcCurrent`
> chore: Add LTC current schemas

- src/pages/race/index.js
Updated 2018 to 2019 for referenced ACS demographic data
> Chore(ACS year): Update Census year

- src/components/pages/data/daily-tweet.js
- Fix issue with timezones in pinned tweets
> chore: Sort tweet by only pinned status

- src/components/pages/data/summary.js
> fix(definitions-panel): include state names in header

- gatsby-config.js
- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/flippable-card.js
- src/components/pages/blog/content-blocks/flippable-card.module.scss
- src/templates/blog-post.js
- Adds a flippable card type to blog posts
> chore: Add flippable cards

- src/components/layout/header/navigation.module.scss
> fix(a11y): Missing focus style on dropdown menus

- src/components/pages/race/dashboard/state-nav.js
Stops reloading the page when users press enter with more than one result
When users press enter and there is more than one
result, this will now jump to the first result.
(Previously, pressing enter with more than one result would no nothing.)
> Update CRDT combobox behavior

- src/components/pages/homepage/visualization-gallery/items/us-map/metrics.js
> chore(homepage-metrics): use 'cases per 100k' instead of 'cases'

- src/components/pages/homepage/visualization-gallery/items/national-chart.js
- src/components/pages/homepage/visualization-gallery/items/national-charts.module.scss
- src/data/navigation/header.yml
- src/pages/data/index.js
- src/templates/state/preprocess-annotations.js
- Makes national charts on the homepage visualization `align-items: flex-end`
> chore: Fix align items in mobile national charts

- src/pages/data/api.js
- src/pages/data/charts.js
- src/pages/data/download.js
> chore: Add warning to API/charts/download page

- src/__tests__/components/layout/__snapshots__/footer.js.snap
- src/__tests__/components/layout/__snapshots__/index.js.snap
- src/components/pages/homepage/visualization-gallery/items/us-map/index.js
- src/components/pages/homepage/visualization-gallery/items/us-map/metrics.js
- Fixes subtitle for hospitalization map
> chore: Allow metrics to define a subtitle

- jest.config.js
- src/components/pages/homepage/visualization-gallery/components/disclaimer.js
- src/components/pages/homepage/visualization-gallery/components/disclaimer.module.scss
- src/components/pages/homepage/visualization-gallery/items/us-map/map.js
- Fixes duplicate "about this data" appearing above the mobile grid
> chore: Hide disclaimer for map on mobile

- src/pages/about/sitemap.js
- Fixes date format in sitemap
> chore: Fix date format for sitemap

- src/components/pages/data/hhs-facilities/map/index.js
- src/components/pages/data/hhs-facilities/map/legend.js
- src/components/pages/data/hhs-facilities/map/legend.module.scss
- src/pages/data/hospital-facilities/index.js
- Adds an indicator of date range to the HHS map
> feat: Add automatic map date to legend

- src/components/pages/data/hhs-facilities/map/legend.js
- Remove date range in map until the date is inferred
> HHS map: Hide date range if missing

- src/pages/race/index.js
Changed 'are dying' to 'have died' in 
* Nationwide, Black people are dying at 1.6 times the rate of white people.
> fix (words): Update verb choice

- src/components/pages/blog/footer/related-posts.module.scss
Moves this overhanging arrow (highlighted in blue) to one line
> chore(related-posts): fix overhanging cta arrow

- gatsby-config.js
- Turns off CSS hashing in development
> feat: Switch off CSS hashing in development

- src/__tests__/components/pages/state/__snapshots__/state-grade.js.snap
- src/__tests__/components/pages/state/state-grade.js
- src/components/common/last-updated.js
- src/components/common/last-updated.module.scss
- src/components/pages/data/state-data.js
- src/components/pages/state/download-data.js
- src/components/pages/state/download-data.module.scss
- src/components/pages/state/preamble.js
- src/components/pages/state/preamble.module.scss
- src/components/pages/state/state-grade.js
- src/components/pages/state/state-grade.module.scss
- src/components/pages/state/state-links.js
- src/components/pages/state/state-links.module.scss
- src/pages/data/index.js
- Remove grades from `/data`
- Make the grade on state pages smaller
> chore: Deemphasize grades

- src/components/utils/seo.js
- src/pages/about-data/data-definitions.js
- src/pages/about-data/total-tests.js
- src/pages/about-data/visualization-guide.js
- src/pages/about/index.js
- src/pages/data/index.js
- src/pages/data/long-term-care/index.js
- src/pages/data/national/cases.js
- src/pages/data/national/deaths.js
- src/pages/data/national/hospitalization.js
- src/pages/data/national/index.js
- src/pages/data/national/tests.js
- src/templates/state/cases.js
- src/templates/state/hospitalization.js
- src/templates/state/index.js
- src/templates/state/long-term-care/index.js
- src/templates/state/outcomes.js
- src/templates/state/tests-antibody.js
- src/templates/state/tests-viral.js
> chore: Add page descriptions to dynamic pages

- gatsby-node.js
- src/components/pages/data/cards/tests-antigen.js
- src/components/pages/data/summary.js
- src/pages/data/index.js
- src/templates/state/index.js
- src/templates/state/tests-antigen.js
> Add antigen tests card, historical page

- src/utilities/csv.js
> fix: Remove deprecated recovered field from US CSV

- src/components/pages/state/preamble.js
- src/components/pages/state/preamble.module.scss
> chore: Fix preamble stacking in mobile

- src/components/pages/blog/content-blocks/table-content-block.module.scss
- Adds shading to content table headers
- Makes content tables full width
- Adds margin to base of table
> chore: Add highlight, full widtht to content tables

- src/components/pages/blog/blog-content.js
Fixes doubly-set language localization in image block size settings
> chore: Fix keep size and mobile settings from CMS

- netlify.toml
Add explicit cache control to race data images.
> chore: Add cache control for race dashboard

- src/components/pages/homepage/visualization-gallery/index.js
- src/components/pages/homepage/visualization-gallery/items/us-map/map.js
- src/components/pages/homepage/visualization-gallery/visualization-gallery.module.scss
> fix(a11y): Add skiplink to visuzation gallery, remove tabindex from map legends

- src/components/pages/data/summary.js
Handle cases where annotations = false before attempting
to iterate over the annotations.
Also updates the national definition panel title to say
'National' instead of 'undefined'.
> fix: national forEach annotation bug

- src/utilities/algolia.js
Remove notes from algolia indexing
> chore: remove notes from state index

- src/components/pages/data/hhs-facilities/map/legend.module.scss
Change legend for N/A facilities in the HHS map
> chore: Change legend for N/A

- gatsby-config.js
- plugins/gatsby-source-covid-tracking-api/gatsby-node.js
- src/components/pages/data/state-data.js
- src/components/pages/data/states.js
- src/components/pages/data/summary.js
- src/pages/data/index.js
- src/templates/state/index.js
- Filters out unused HHS nodes
- Adds field transform to default API plugin
- Rewrites some HHS queries to make them simpler
> chore(perf): Remove unused HHS data

- src/components/pages/homepage/visualization-gallery/items/us-map/grid.js
> fix: Error where map modal wouldn't hide for US

- src/components/charts/tableau.js
- src/components/pages/blog/blog-content.js
Make tableau charts wider than the text area in blog posts
> feat: Fuller-width for tableau charts

- src/__tests__/components/charts/__snapshots__/bar-chart.js.snap
- src/components/charts/bar-chart.js
- src/components/layout/header/data-warning.js
- src/components/layout/header/index.js
- src/components/layout/header/rt-live-warning.js
> chore: Add rt.live warning

- src/pages/data/charts.js
- src/pages/data/index.js
Removes daily tweet from data page
> chore: remove daily tweet

- src/components/pages/data/long-term-care/download-links.js
- static/_redirects
> fix: Wrong history link

- src/components/pages/state/race-ethnicity/filtered-notice.js
- src/components/pages/state/race-ethnicity/historical-tables.js
* removes empty table rows from states that began reporting late
* adds a `FilteredNotice` component to indicate the omission to users
> fix(crdt-historical): remove empty table rows

- src/components/pages/state/long-term-care/preamble.js
- src/components/pages/state/long-term-care/preamble.module.scss
Adds last updated date to LTC state pages
> chore: Add date to LTC preamble

- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/image-content-block.js
- src/templates/blog-post.js
- Adds markdown support for a new "Long caption" field in image blocks.
> feat: Add markdown support for captions

- src/components/pages/data/hhs-facilities/map/legend.js
Fixes map context toggle in HHS map
> chore: Fix map context in HHS map

- src/__tests__/components/common/__snapshots__/table-of-contents.js.snap
- src/__tests__/components/common/table-of-contents.js
- src/components/common/table-of-contents.js
- src/components/common/table-of-contents.module.scss
- src/templates/content.js
Adds support for h1 in TOCs. Fixes #1337
> chore: Add nesting to TOC

- gatsby-config.js
- src/components/pages/data/long-term-care/map/index.js
- src/components/pages/state/long-term-care/chart.js
- src/components/pages/state/long-term-care/facilities.js
- src/templates/state/long-term-care/index.js
- src/utilities/schema.js
- Moves facility listing to mapbox as a source
- Removes broken tooltip from LTC charts
> chore: Add mapbox facility list

- src/components/pages/blog/blog-content.js
- src/components/pages/blog/content-blocks/table-content-block.js
- src/templates/blog-post.js
- Adds caption to table blocks
> feat: Table captions

- src/components/pages/blog/content-blocks/table-content-block.js
- src/components/pages/blog/content-blocks/table-content-block.module.scss
- Puts the caption into a real `<caption>` tag and fixes full width.
> chore: Fix text align and put caption into tag

- gatsby-config.js
- src/components/charts/line-chart.js
- src/components/pages/data/cards/hhs-tests-viral.js
- src/components/pages/data/state-data.js
- src/components/pages/data/states.js
- src/components/pages/data/summary.js
- src/pages/data/index.js
- src/templates/state/index.js
- Adds new `hhsTesting` data source
- Adds a new HHS Testing card
> feat: Add new HHS testing card

- src/components/pages/state/race-ethnicity/utils/generate-table-labels.js
fixes the "per100k" column labels in the historical tables for
states that report race and ethnicity separately
> fix(crdt-historical): explicitly define ethnicity columns

- src/__tests__/components/pages/state/__snapshots__/state-notes.js.snap
- src/__tests__/components/pages/state/state-notes.js
- src/components/pages/state/state-notes.js
- src/templates/state/long-term-care/history.js
- Removes the lede paragraph from the LTC historic pages
> chore: Remove LTC historic page lede

- src/components/charts/tableau.js
> chore: Remove Tableau outage warning

- src/components/pages/about-data/data-summary.js
- Fix redundant federal resources link
> chore: Remove duplicate federal resources link

- src/components/pages/about-data/federal-resources.js
> fix: Don't show category headers when no resources exist

- src/templates/state/notes.js
Fixes missing state grades on the notes page.
> fix: Missing state grade assessments

- .circleci/config.yml
- README.md
- Removes unneeded setup step
- Removes unused coverage reporter
> chore: Cleanup CI work, remove test coverage

- src/utilities/ltc-totals.js
- Fixes missing addition in the LTC totals
> fix: Bad total facilities math in LTC

- src/templates/state/long-term-care/index.js
- Adds source links and facility notes to the LTC page of each state
> chore: Add more notes to LTC page

- HISTORY.md
- README.md
- Adds a history page with an overview of the website's history.
> feat: Add history page

- src/components/pages/homepage/impact.js
Adds list of awards to homepage impact section.
> feat: Add awards to impact section

- src/components/pages/data/api/change-log.js
> chore: Remove link to status page
